// Code generated by go-swagger; DO NOT EDIT.

package mobiledevices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteMobileDeviceByMacAddressReader is a Reader for the DeleteMobileDeviceByMacAddress structure.
type DeleteMobileDeviceByMacAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMobileDeviceByMacAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMobileDeviceByMacAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /mobiledevices/macaddress/{macaddress}] deleteMobileDeviceByMacAddress", response, response.Code())
	}
}

// NewDeleteMobileDeviceByMacAddressOK creates a DeleteMobileDeviceByMacAddressOK with default headers values
func NewDeleteMobileDeviceByMacAddressOK() *DeleteMobileDeviceByMacAddressOK {
	return &DeleteMobileDeviceByMacAddressOK{}
}

/*
DeleteMobileDeviceByMacAddressOK describes a response with status code 200, with default header values.

OK
*/
type DeleteMobileDeviceByMacAddressOK struct {
}

// IsSuccess returns true when this delete mobile device by mac address o k response has a 2xx status code
func (o *DeleteMobileDeviceByMacAddressOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete mobile device by mac address o k response has a 3xx status code
func (o *DeleteMobileDeviceByMacAddressOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete mobile device by mac address o k response has a 4xx status code
func (o *DeleteMobileDeviceByMacAddressOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete mobile device by mac address o k response has a 5xx status code
func (o *DeleteMobileDeviceByMacAddressOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete mobile device by mac address o k response a status code equal to that given
func (o *DeleteMobileDeviceByMacAddressOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete mobile device by mac address o k response
func (o *DeleteMobileDeviceByMacAddressOK) Code() int {
	return 200
}

func (o *DeleteMobileDeviceByMacAddressOK) Error() string {
	return fmt.Sprintf("[DELETE /mobiledevices/macaddress/{macaddress}][%d] deleteMobileDeviceByMacAddressOK ", 200)
}

func (o *DeleteMobileDeviceByMacAddressOK) String() string {
	return fmt.Sprintf("[DELETE /mobiledevices/macaddress/{macaddress}][%d] deleteMobileDeviceByMacAddressOK ", 200)
}

func (o *DeleteMobileDeviceByMacAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
