// Code generated by go-swagger; DO NOT EDIT.

package mobiledevices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateMobileDeviceByUDIDReader is a Reader for the UpdateMobileDeviceByUDID structure.
type UpdateMobileDeviceByUDIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMobileDeviceByUDIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateMobileDeviceByUDIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /mobiledevices/udid/{udid}] updateMobileDeviceByUDID", response, response.Code())
	}
}

// NewUpdateMobileDeviceByUDIDCreated creates a UpdateMobileDeviceByUDIDCreated with default headers values
func NewUpdateMobileDeviceByUDIDCreated() *UpdateMobileDeviceByUDIDCreated {
	return &UpdateMobileDeviceByUDIDCreated{}
}

/*
UpdateMobileDeviceByUDIDCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateMobileDeviceByUDIDCreated struct {
}

// IsSuccess returns true when this update mobile device by u d Id created response has a 2xx status code
func (o *UpdateMobileDeviceByUDIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update mobile device by u d Id created response has a 3xx status code
func (o *UpdateMobileDeviceByUDIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update mobile device by u d Id created response has a 4xx status code
func (o *UpdateMobileDeviceByUDIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update mobile device by u d Id created response has a 5xx status code
func (o *UpdateMobileDeviceByUDIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update mobile device by u d Id created response a status code equal to that given
func (o *UpdateMobileDeviceByUDIDCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update mobile device by u d Id created response
func (o *UpdateMobileDeviceByUDIDCreated) Code() int {
	return 201
}

func (o *UpdateMobileDeviceByUDIDCreated) Error() string {
	return fmt.Sprintf("[PUT /mobiledevices/udid/{udid}][%d] updateMobileDeviceByUDIdCreated ", 201)
}

func (o *UpdateMobileDeviceByUDIDCreated) String() string {
	return fmt.Sprintf("[PUT /mobiledevices/udid/{udid}][%d] updateMobileDeviceByUDIdCreated ", 201)
}

func (o *UpdateMobileDeviceByUDIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
