// Code generated by go-swagger; DO NOT EDIT.

package mobiledevices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateMobileDeviceByNameReader is a Reader for the UpdateMobileDeviceByName structure.
type UpdateMobileDeviceByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMobileDeviceByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateMobileDeviceByNameCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /mobiledevices/name/{name}] updateMobileDeviceByName", response, response.Code())
	}
}

// NewUpdateMobileDeviceByNameCreated creates a UpdateMobileDeviceByNameCreated with default headers values
func NewUpdateMobileDeviceByNameCreated() *UpdateMobileDeviceByNameCreated {
	return &UpdateMobileDeviceByNameCreated{}
}

/*
UpdateMobileDeviceByNameCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateMobileDeviceByNameCreated struct {
}

// IsSuccess returns true when this update mobile device by name created response has a 2xx status code
func (o *UpdateMobileDeviceByNameCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update mobile device by name created response has a 3xx status code
func (o *UpdateMobileDeviceByNameCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update mobile device by name created response has a 4xx status code
func (o *UpdateMobileDeviceByNameCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update mobile device by name created response has a 5xx status code
func (o *UpdateMobileDeviceByNameCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update mobile device by name created response a status code equal to that given
func (o *UpdateMobileDeviceByNameCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update mobile device by name created response
func (o *UpdateMobileDeviceByNameCreated) Code() int {
	return 201
}

func (o *UpdateMobileDeviceByNameCreated) Error() string {
	return fmt.Sprintf("[PUT /mobiledevices/name/{name}][%d] updateMobileDeviceByNameCreated ", 201)
}

func (o *UpdateMobileDeviceByNameCreated) String() string {
	return fmt.Sprintf("[PUT /mobiledevices/name/{name}][%d] updateMobileDeviceByNameCreated ", 201)
}

func (o *UpdateMobileDeviceByNameCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
