// Code generated by go-swagger; DO NOT EDIT.

package macapplications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindMacappsParams creates a new FindMacappsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindMacappsParams() *FindMacappsParams {
	return &FindMacappsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindMacappsParamsWithTimeout creates a new FindMacappsParams object
// with the ability to set a timeout on a request.
func NewFindMacappsParamsWithTimeout(timeout time.Duration) *FindMacappsParams {
	return &FindMacappsParams{
		timeout: timeout,
	}
}

// NewFindMacappsParamsWithContext creates a new FindMacappsParams object
// with the ability to set a context for a request.
func NewFindMacappsParamsWithContext(ctx context.Context) *FindMacappsParams {
	return &FindMacappsParams{
		Context: ctx,
	}
}

// NewFindMacappsParamsWithHTTPClient creates a new FindMacappsParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindMacappsParamsWithHTTPClient(client *http.Client) *FindMacappsParams {
	return &FindMacappsParams{
		HTTPClient: client,
	}
}

/*
FindMacappsParams contains all the parameters to send to the API endpoint

	for the find macapps operation.

	Typically these are written to a http.Request.
*/
type FindMacappsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find macapps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindMacappsParams) WithDefaults() *FindMacappsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find macapps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindMacappsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find macapps params
func (o *FindMacappsParams) WithTimeout(timeout time.Duration) *FindMacappsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find macapps params
func (o *FindMacappsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find macapps params
func (o *FindMacappsParams) WithContext(ctx context.Context) *FindMacappsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find macapps params
func (o *FindMacappsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find macapps params
func (o *FindMacappsParams) WithHTTPClient(client *http.Client) *FindMacappsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find macapps params
func (o *FindMacappsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindMacappsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
