// Code generated by go-swagger; DO NOT EDIT.

package peripherals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdatePeripheralByIDReader is a Reader for the UpdatePeripheralByID structure.
type UpdatePeripheralByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePeripheralByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdatePeripheralByIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /peripherals/id/{id}] updatePeripheralById", response, response.Code())
	}
}

// NewUpdatePeripheralByIDCreated creates a UpdatePeripheralByIDCreated with default headers values
func NewUpdatePeripheralByIDCreated() *UpdatePeripheralByIDCreated {
	return &UpdatePeripheralByIDCreated{}
}

/*
UpdatePeripheralByIDCreated describes a response with status code 201, with default header values.

Created
*/
type UpdatePeripheralByIDCreated struct {
}

// IsSuccess returns true when this update peripheral by Id created response has a 2xx status code
func (o *UpdatePeripheralByIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update peripheral by Id created response has a 3xx status code
func (o *UpdatePeripheralByIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update peripheral by Id created response has a 4xx status code
func (o *UpdatePeripheralByIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update peripheral by Id created response has a 5xx status code
func (o *UpdatePeripheralByIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update peripheral by Id created response a status code equal to that given
func (o *UpdatePeripheralByIDCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update peripheral by Id created response
func (o *UpdatePeripheralByIDCreated) Code() int {
	return 201
}

func (o *UpdatePeripheralByIDCreated) Error() string {
	return fmt.Sprintf("[PUT /peripherals/id/{id}][%d] updatePeripheralByIdCreated ", 201)
}

func (o *UpdatePeripheralByIDCreated) String() string {
	return fmt.Sprintf("[PUT /peripherals/id/{id}][%d] updatePeripheralByIdCreated ", 201)
}

func (o *UpdatePeripheralByIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
