// Code generated by go-swagger; DO NOT EDIT.

package patchavailabletitles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new patchavailabletitles API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for patchavailabletitles API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PatchavailabletitlesSourceidByIDGet(params *PatchavailabletitlesSourceidByIDGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchavailabletitlesSourceidByIDGetOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
PatchavailabletitlesSourceidByIDGet finds all available title from a source by ID
*/
func (a *Client) PatchavailabletitlesSourceidByIDGet(params *PatchavailabletitlesSourceidByIDGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchavailabletitlesSourceidByIDGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchavailabletitlesSourceidByIDGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PatchavailabletitlesSourceidByIdGet",
		Method:             "GET",
		PathPattern:        "/patchavailabletitles/sourceid/{id}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/xml"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PatchavailabletitlesSourceidByIDGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PatchavailabletitlesSourceidByIDGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PatchavailabletitlesSourceidByIdGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
