// Code generated by go-swagger; DO NOT EDIT.

package activationcode

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateActivationCodeReader is a Reader for the UpdateActivationCode structure.
type UpdateActivationCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateActivationCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateActivationCodeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /activationcode] updateActivationCode", response, response.Code())
	}
}

// NewUpdateActivationCodeCreated creates a UpdateActivationCodeCreated with default headers values
func NewUpdateActivationCodeCreated() *UpdateActivationCodeCreated {
	return &UpdateActivationCodeCreated{}
}

/*
UpdateActivationCodeCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateActivationCodeCreated struct {
}

// IsSuccess returns true when this update activation code created response has a 2xx status code
func (o *UpdateActivationCodeCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update activation code created response has a 3xx status code
func (o *UpdateActivationCodeCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update activation code created response has a 4xx status code
func (o *UpdateActivationCodeCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update activation code created response has a 5xx status code
func (o *UpdateActivationCodeCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update activation code created response a status code equal to that given
func (o *UpdateActivationCodeCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update activation code created response
func (o *UpdateActivationCodeCreated) Code() int {
	return 201
}

func (o *UpdateActivationCodeCreated) Error() string {
	return fmt.Sprintf("[PUT /activationcode][%d] updateActivationCodeCreated ", 201)
}

func (o *UpdateActivationCodeCreated) String() string {
	return fmt.Sprintf("[PUT /activationcode][%d] updateActivationCodeCreated ", 201)
}

func (o *UpdateActivationCodeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
