// Code generated by go-swagger; DO NOT EDIT.

package licensedsoftware

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteLicensedSoftwareByNameParams creates a new DeleteLicensedSoftwareByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLicensedSoftwareByNameParams() *DeleteLicensedSoftwareByNameParams {
	return &DeleteLicensedSoftwareByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLicensedSoftwareByNameParamsWithTimeout creates a new DeleteLicensedSoftwareByNameParams object
// with the ability to set a timeout on a request.
func NewDeleteLicensedSoftwareByNameParamsWithTimeout(timeout time.Duration) *DeleteLicensedSoftwareByNameParams {
	return &DeleteLicensedSoftwareByNameParams{
		timeout: timeout,
	}
}

// NewDeleteLicensedSoftwareByNameParamsWithContext creates a new DeleteLicensedSoftwareByNameParams object
// with the ability to set a context for a request.
func NewDeleteLicensedSoftwareByNameParamsWithContext(ctx context.Context) *DeleteLicensedSoftwareByNameParams {
	return &DeleteLicensedSoftwareByNameParams{
		Context: ctx,
	}
}

// NewDeleteLicensedSoftwareByNameParamsWithHTTPClient creates a new DeleteLicensedSoftwareByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLicensedSoftwareByNameParamsWithHTTPClient(client *http.Client) *DeleteLicensedSoftwareByNameParams {
	return &DeleteLicensedSoftwareByNameParams{
		HTTPClient: client,
	}
}

/*
DeleteLicensedSoftwareByNameParams contains all the parameters to send to the API endpoint

	for the delete licensed software by name operation.

	Typically these are written to a http.Request.
*/
type DeleteLicensedSoftwareByNameParams struct {

	/* Name.

	   Name value to filter by
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete licensed software by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLicensedSoftwareByNameParams) WithDefaults() *DeleteLicensedSoftwareByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete licensed software by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLicensedSoftwareByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) WithTimeout(timeout time.Duration) *DeleteLicensedSoftwareByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) WithContext(ctx context.Context) *DeleteLicensedSoftwareByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) WithHTTPClient(client *http.Client) *DeleteLicensedSoftwareByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) WithName(name string) *DeleteLicensedSoftwareByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete licensed software by name params
func (o *DeleteLicensedSoftwareByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLicensedSoftwareByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
