// Code generated by go-swagger; DO NOT EDIT.

package mobiledeviceenrollmentprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateMobileDeviceEnrollmentProfileByNameParams creates a new UpdateMobileDeviceEnrollmentProfileByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateMobileDeviceEnrollmentProfileByNameParams() *UpdateMobileDeviceEnrollmentProfileByNameParams {
	return &UpdateMobileDeviceEnrollmentProfileByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMobileDeviceEnrollmentProfileByNameParamsWithTimeout creates a new UpdateMobileDeviceEnrollmentProfileByNameParams object
// with the ability to set a timeout on a request.
func NewUpdateMobileDeviceEnrollmentProfileByNameParamsWithTimeout(timeout time.Duration) *UpdateMobileDeviceEnrollmentProfileByNameParams {
	return &UpdateMobileDeviceEnrollmentProfileByNameParams{
		timeout: timeout,
	}
}

// NewUpdateMobileDeviceEnrollmentProfileByNameParamsWithContext creates a new UpdateMobileDeviceEnrollmentProfileByNameParams object
// with the ability to set a context for a request.
func NewUpdateMobileDeviceEnrollmentProfileByNameParamsWithContext(ctx context.Context) *UpdateMobileDeviceEnrollmentProfileByNameParams {
	return &UpdateMobileDeviceEnrollmentProfileByNameParams{
		Context: ctx,
	}
}

// NewUpdateMobileDeviceEnrollmentProfileByNameParamsWithHTTPClient creates a new UpdateMobileDeviceEnrollmentProfileByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateMobileDeviceEnrollmentProfileByNameParamsWithHTTPClient(client *http.Client) *UpdateMobileDeviceEnrollmentProfileByNameParams {
	return &UpdateMobileDeviceEnrollmentProfileByNameParams{
		HTTPClient: client,
	}
}

/*
UpdateMobileDeviceEnrollmentProfileByNameParams contains all the parameters to send to the API endpoint

	for the update mobile device enrollment profile by name operation.

	Typically these are written to a http.Request.
*/
type UpdateMobileDeviceEnrollmentProfileByNameParams struct {

	/* Name.

	   Name value to filter by
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update mobile device enrollment profile by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) WithDefaults() *UpdateMobileDeviceEnrollmentProfileByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update mobile device enrollment profile by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) WithTimeout(timeout time.Duration) *UpdateMobileDeviceEnrollmentProfileByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) WithContext(ctx context.Context) *UpdateMobileDeviceEnrollmentProfileByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) WithHTTPClient(client *http.Client) *UpdateMobileDeviceEnrollmentProfileByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) WithName(name string) *UpdateMobileDeviceEnrollmentProfileByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update mobile device enrollment profile by name params
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMobileDeviceEnrollmentProfileByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
