// Code generated by go-swagger; DO NOT EDIT.

package computerhardwaresoftwarereports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindComputerHardwareSoftwareReportsByMacAddressReader is a Reader for the FindComputerHardwareSoftwareReportsByMacAddress structure.
type FindComputerHardwareSoftwareReportsByMacAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindComputerHardwareSoftwareReportsByMacAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindComputerHardwareSoftwareReportsByMacAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /computerhardwaresoftwarereports/macaddress/{macaddress}/{start_date}_{end_date}] findComputerHardwareSoftwareReportsByMacAddress", response, response.Code())
	}
}

// NewFindComputerHardwareSoftwareReportsByMacAddressOK creates a FindComputerHardwareSoftwareReportsByMacAddressOK with default headers values
func NewFindComputerHardwareSoftwareReportsByMacAddressOK() *FindComputerHardwareSoftwareReportsByMacAddressOK {
	return &FindComputerHardwareSoftwareReportsByMacAddressOK{}
}

/*
FindComputerHardwareSoftwareReportsByMacAddressOK describes a response with status code 200, with default header values.

OK
*/
type FindComputerHardwareSoftwareReportsByMacAddressOK struct {
	Payload *models.ComputerHardwareSoftwareReports
}

// IsSuccess returns true when this find computer hardware software reports by mac address o k response has a 2xx status code
func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find computer hardware software reports by mac address o k response has a 3xx status code
func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find computer hardware software reports by mac address o k response has a 4xx status code
func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find computer hardware software reports by mac address o k response has a 5xx status code
func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find computer hardware software reports by mac address o k response a status code equal to that given
func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find computer hardware software reports by mac address o k response
func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) Code() int {
	return 200
}

func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) Error() string {
	return fmt.Sprintf("[GET /computerhardwaresoftwarereports/macaddress/{macaddress}/{start_date}_{end_date}][%d] findComputerHardwareSoftwareReportsByMacAddressOK  %+v", 200, o.Payload)
}

func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) String() string {
	return fmt.Sprintf("[GET /computerhardwaresoftwarereports/macaddress/{macaddress}/{start_date}_{end_date}][%d] findComputerHardwareSoftwareReportsByMacAddressOK  %+v", 200, o.Payload)
}

func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) GetPayload() *models.ComputerHardwareSoftwareReports {
	return o.Payload
}

func (o *FindComputerHardwareSoftwareReportsByMacAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComputerHardwareSoftwareReports)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
