// Code generated by go-swagger; DO NOT EDIT.

package jsonwebtokenconfigurations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteJSONWebTokenConfigurationByIDParams creates a new DeleteJSONWebTokenConfigurationByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteJSONWebTokenConfigurationByIDParams() *DeleteJSONWebTokenConfigurationByIDParams {
	return &DeleteJSONWebTokenConfigurationByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteJSONWebTokenConfigurationByIDParamsWithTimeout creates a new DeleteJSONWebTokenConfigurationByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteJSONWebTokenConfigurationByIDParamsWithTimeout(timeout time.Duration) *DeleteJSONWebTokenConfigurationByIDParams {
	return &DeleteJSONWebTokenConfigurationByIDParams{
		timeout: timeout,
	}
}

// NewDeleteJSONWebTokenConfigurationByIDParamsWithContext creates a new DeleteJSONWebTokenConfigurationByIDParams object
// with the ability to set a context for a request.
func NewDeleteJSONWebTokenConfigurationByIDParamsWithContext(ctx context.Context) *DeleteJSONWebTokenConfigurationByIDParams {
	return &DeleteJSONWebTokenConfigurationByIDParams{
		Context: ctx,
	}
}

// NewDeleteJSONWebTokenConfigurationByIDParamsWithHTTPClient creates a new DeleteJSONWebTokenConfigurationByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteJSONWebTokenConfigurationByIDParamsWithHTTPClient(client *http.Client) *DeleteJSONWebTokenConfigurationByIDParams {
	return &DeleteJSONWebTokenConfigurationByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteJSONWebTokenConfigurationByIDParams contains all the parameters to send to the API endpoint

	for the delete Json web token configuration by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteJSONWebTokenConfigurationByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete Json web token configuration by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteJSONWebTokenConfigurationByIDParams) WithDefaults() *DeleteJSONWebTokenConfigurationByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete Json web token configuration by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteJSONWebTokenConfigurationByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) WithTimeout(timeout time.Duration) *DeleteJSONWebTokenConfigurationByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) WithContext(ctx context.Context) *DeleteJSONWebTokenConfigurationByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) WithHTTPClient(client *http.Client) *DeleteJSONWebTokenConfigurationByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) WithID(id string) *DeleteJSONWebTokenConfigurationByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete Json web token configuration by Id params
func (o *DeleteJSONWebTokenConfigurationByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteJSONWebTokenConfigurationByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
