// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateCategoryByIDReader is a Reader for the CreateCategoryByID structure.
type CreateCategoryByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCategoryByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateCategoryByIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /categories/id/{id}] createCategoryById", response, response.Code())
	}
}

// NewCreateCategoryByIDCreated creates a CreateCategoryByIDCreated with default headers values
func NewCreateCategoryByIDCreated() *CreateCategoryByIDCreated {
	return &CreateCategoryByIDCreated{}
}

/*
CreateCategoryByIDCreated describes a response with status code 201, with default header values.

Created
*/
type CreateCategoryByIDCreated struct {
}

// IsSuccess returns true when this create category by Id created response has a 2xx status code
func (o *CreateCategoryByIDCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create category by Id created response has a 3xx status code
func (o *CreateCategoryByIDCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create category by Id created response has a 4xx status code
func (o *CreateCategoryByIDCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create category by Id created response has a 5xx status code
func (o *CreateCategoryByIDCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create category by Id created response a status code equal to that given
func (o *CreateCategoryByIDCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create category by Id created response
func (o *CreateCategoryByIDCreated) Code() int {
	return 201
}

func (o *CreateCategoryByIDCreated) Error() string {
	return fmt.Sprintf("[POST /categories/id/{id}][%d] createCategoryByIdCreated ", 201)
}

func (o *CreateCategoryByIDCreated) String() string {
	return fmt.Sprintf("[POST /categories/id/{id}][%d] createCategoryByIdCreated ", 201)
}

func (o *CreateCategoryByIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
