// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteCategoryByIDReader is a Reader for the DeleteCategoryByID structure.
type DeleteCategoryByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCategoryByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteCategoryByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /categories/id/{id}] deleteCategoryById", response, response.Code())
	}
}

// NewDeleteCategoryByIDOK creates a DeleteCategoryByIDOK with default headers values
func NewDeleteCategoryByIDOK() *DeleteCategoryByIDOK {
	return &DeleteCategoryByIDOK{}
}

/*
DeleteCategoryByIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteCategoryByIDOK struct {
}

// IsSuccess returns true when this delete category by Id o k response has a 2xx status code
func (o *DeleteCategoryByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete category by Id o k response has a 3xx status code
func (o *DeleteCategoryByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete category by Id o k response has a 4xx status code
func (o *DeleteCategoryByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete category by Id o k response has a 5xx status code
func (o *DeleteCategoryByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete category by Id o k response a status code equal to that given
func (o *DeleteCategoryByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete category by Id o k response
func (o *DeleteCategoryByIDOK) Code() int {
	return 200
}

func (o *DeleteCategoryByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /categories/id/{id}][%d] deleteCategoryByIdOK ", 200)
}

func (o *DeleteCategoryByIDOK) String() string {
	return fmt.Sprintf("[DELETE /categories/id/{id}][%d] deleteCategoryByIdOK ", 200)
}

func (o *DeleteCategoryByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
