// Code generated by go-swagger; DO NOT EDIT.

package mobiledeviceinvitations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateMobileDeviceInvitationsByInvitationParams creates a new CreateMobileDeviceInvitationsByInvitationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMobileDeviceInvitationsByInvitationParams() *CreateMobileDeviceInvitationsByInvitationParams {
	return &CreateMobileDeviceInvitationsByInvitationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMobileDeviceInvitationsByInvitationParamsWithTimeout creates a new CreateMobileDeviceInvitationsByInvitationParams object
// with the ability to set a timeout on a request.
func NewCreateMobileDeviceInvitationsByInvitationParamsWithTimeout(timeout time.Duration) *CreateMobileDeviceInvitationsByInvitationParams {
	return &CreateMobileDeviceInvitationsByInvitationParams{
		timeout: timeout,
	}
}

// NewCreateMobileDeviceInvitationsByInvitationParamsWithContext creates a new CreateMobileDeviceInvitationsByInvitationParams object
// with the ability to set a context for a request.
func NewCreateMobileDeviceInvitationsByInvitationParamsWithContext(ctx context.Context) *CreateMobileDeviceInvitationsByInvitationParams {
	return &CreateMobileDeviceInvitationsByInvitationParams{
		Context: ctx,
	}
}

// NewCreateMobileDeviceInvitationsByInvitationParamsWithHTTPClient creates a new CreateMobileDeviceInvitationsByInvitationParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMobileDeviceInvitationsByInvitationParamsWithHTTPClient(client *http.Client) *CreateMobileDeviceInvitationsByInvitationParams {
	return &CreateMobileDeviceInvitationsByInvitationParams{
		HTTPClient: client,
	}
}

/*
CreateMobileDeviceInvitationsByInvitationParams contains all the parameters to send to the API endpoint

	for the create mobile device invitations by invitation operation.

	Typically these are written to a http.Request.
*/
type CreateMobileDeviceInvitationsByInvitationParams struct {

	/* Invitation.

	   Invitation value to filter by
	*/
	Invitation int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create mobile device invitations by invitation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMobileDeviceInvitationsByInvitationParams) WithDefaults() *CreateMobileDeviceInvitationsByInvitationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create mobile device invitations by invitation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMobileDeviceInvitationsByInvitationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) WithTimeout(timeout time.Duration) *CreateMobileDeviceInvitationsByInvitationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) WithContext(ctx context.Context) *CreateMobileDeviceInvitationsByInvitationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) WithHTTPClient(client *http.Client) *CreateMobileDeviceInvitationsByInvitationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInvitation adds the invitation to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) WithInvitation(invitation int64) *CreateMobileDeviceInvitationsByInvitationParams {
	o.SetInvitation(invitation)
	return o
}

// SetInvitation adds the invitation to the create mobile device invitations by invitation params
func (o *CreateMobileDeviceInvitationsByInvitationParams) SetInvitation(invitation int64) {
	o.Invitation = invitation
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMobileDeviceInvitationsByInvitationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param invitation
	if err := r.SetPathParam("invitation", swag.FormatInt64(o.Invitation)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
