// Code generated by go-swagger; DO NOT EDIT.

package ldapservers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateLDAPServerByIDParams creates a new CreateLDAPServerByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateLDAPServerByIDParams() *CreateLDAPServerByIDParams {
	return &CreateLDAPServerByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateLDAPServerByIDParamsWithTimeout creates a new CreateLDAPServerByIDParams object
// with the ability to set a timeout on a request.
func NewCreateLDAPServerByIDParamsWithTimeout(timeout time.Duration) *CreateLDAPServerByIDParams {
	return &CreateLDAPServerByIDParams{
		timeout: timeout,
	}
}

// NewCreateLDAPServerByIDParamsWithContext creates a new CreateLDAPServerByIDParams object
// with the ability to set a context for a request.
func NewCreateLDAPServerByIDParamsWithContext(ctx context.Context) *CreateLDAPServerByIDParams {
	return &CreateLDAPServerByIDParams{
		Context: ctx,
	}
}

// NewCreateLDAPServerByIDParamsWithHTTPClient creates a new CreateLDAPServerByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateLDAPServerByIDParamsWithHTTPClient(client *http.Client) *CreateLDAPServerByIDParams {
	return &CreateLDAPServerByIDParams{
		HTTPClient: client,
	}
}

/*
CreateLDAPServerByIDParams contains all the parameters to send to the API endpoint

	for the create l d a p server by Id operation.

	Typically these are written to a http.Request.
*/
type CreateLDAPServerByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create l d a p server by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateLDAPServerByIDParams) WithDefaults() *CreateLDAPServerByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create l d a p server by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateLDAPServerByIDParams) SetDefaults() {
	var (
		idDefault = int64(0)
	)

	val := CreateLDAPServerByIDParams{
		ID: idDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) WithTimeout(timeout time.Duration) *CreateLDAPServerByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) WithContext(ctx context.Context) *CreateLDAPServerByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) WithHTTPClient(client *http.Client) *CreateLDAPServerByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) WithID(id int64) *CreateLDAPServerByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create l d a p server by Id params
func (o *CreateLDAPServerByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateLDAPServerByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
