// Code generated by go-swagger; DO NOT EDIT.

package ldapservers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindLDAPServersByIDParams creates a new FindLDAPServersByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindLDAPServersByIDParams() *FindLDAPServersByIDParams {
	return &FindLDAPServersByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindLDAPServersByIDParamsWithTimeout creates a new FindLDAPServersByIDParams object
// with the ability to set a timeout on a request.
func NewFindLDAPServersByIDParamsWithTimeout(timeout time.Duration) *FindLDAPServersByIDParams {
	return &FindLDAPServersByIDParams{
		timeout: timeout,
	}
}

// NewFindLDAPServersByIDParamsWithContext creates a new FindLDAPServersByIDParams object
// with the ability to set a context for a request.
func NewFindLDAPServersByIDParamsWithContext(ctx context.Context) *FindLDAPServersByIDParams {
	return &FindLDAPServersByIDParams{
		Context: ctx,
	}
}

// NewFindLDAPServersByIDParamsWithHTTPClient creates a new FindLDAPServersByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindLDAPServersByIDParamsWithHTTPClient(client *http.Client) *FindLDAPServersByIDParams {
	return &FindLDAPServersByIDParams{
		HTTPClient: client,
	}
}

/*
FindLDAPServersByIDParams contains all the parameters to send to the API endpoint

	for the find l d a p servers by Id operation.

	Typically these are written to a http.Request.
*/
type FindLDAPServersByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find l d a p servers by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindLDAPServersByIDParams) WithDefaults() *FindLDAPServersByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find l d a p servers by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindLDAPServersByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) WithTimeout(timeout time.Duration) *FindLDAPServersByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) WithContext(ctx context.Context) *FindLDAPServersByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) WithHTTPClient(client *http.Client) *FindLDAPServersByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) WithID(id int64) *FindLDAPServersByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find l d a p servers by Id params
func (o *FindLDAPServersByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindLDAPServersByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
