// Code generated by go-swagger; DO NOT EDIT.

package ldapservers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindLDAPServersParams creates a new FindLDAPServersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindLDAPServersParams() *FindLDAPServersParams {
	return &FindLDAPServersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindLDAPServersParamsWithTimeout creates a new FindLDAPServersParams object
// with the ability to set a timeout on a request.
func NewFindLDAPServersParamsWithTimeout(timeout time.Duration) *FindLDAPServersParams {
	return &FindLDAPServersParams{
		timeout: timeout,
	}
}

// NewFindLDAPServersParamsWithContext creates a new FindLDAPServersParams object
// with the ability to set a context for a request.
func NewFindLDAPServersParamsWithContext(ctx context.Context) *FindLDAPServersParams {
	return &FindLDAPServersParams{
		Context: ctx,
	}
}

// NewFindLDAPServersParamsWithHTTPClient creates a new FindLDAPServersParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindLDAPServersParamsWithHTTPClient(client *http.Client) *FindLDAPServersParams {
	return &FindLDAPServersParams{
		HTTPClient: client,
	}
}

/*
FindLDAPServersParams contains all the parameters to send to the API endpoint

	for the find l d a p servers operation.

	Typically these are written to a http.Request.
*/
type FindLDAPServersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find l d a p servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindLDAPServersParams) WithDefaults() *FindLDAPServersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find l d a p servers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindLDAPServersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find l d a p servers params
func (o *FindLDAPServersParams) WithTimeout(timeout time.Duration) *FindLDAPServersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find l d a p servers params
func (o *FindLDAPServersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find l d a p servers params
func (o *FindLDAPServersParams) WithContext(ctx context.Context) *FindLDAPServersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find l d a p servers params
func (o *FindLDAPServersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find l d a p servers params
func (o *FindLDAPServersParams) WithHTTPClient(client *http.Client) *FindLDAPServersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find l d a p servers params
func (o *FindLDAPServersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindLDAPServersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
