// Code generated by go-swagger; DO NOT EDIT.

package softwareupdateservers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateSoftwareUpdateServerByNameReader is a Reader for the UpdateSoftwareUpdateServerByName structure.
type UpdateSoftwareUpdateServerByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSoftwareUpdateServerByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateSoftwareUpdateServerByNameCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /softwareupdateservers/name/{name}] updateSoftwareUpdateServerByName", response, response.Code())
	}
}

// NewUpdateSoftwareUpdateServerByNameCreated creates a UpdateSoftwareUpdateServerByNameCreated with default headers values
func NewUpdateSoftwareUpdateServerByNameCreated() *UpdateSoftwareUpdateServerByNameCreated {
	return &UpdateSoftwareUpdateServerByNameCreated{}
}

/*
UpdateSoftwareUpdateServerByNameCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateSoftwareUpdateServerByNameCreated struct {
}

// IsSuccess returns true when this update software update server by name created response has a 2xx status code
func (o *UpdateSoftwareUpdateServerByNameCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update software update server by name created response has a 3xx status code
func (o *UpdateSoftwareUpdateServerByNameCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update software update server by name created response has a 4xx status code
func (o *UpdateSoftwareUpdateServerByNameCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update software update server by name created response has a 5xx status code
func (o *UpdateSoftwareUpdateServerByNameCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update software update server by name created response a status code equal to that given
func (o *UpdateSoftwareUpdateServerByNameCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update software update server by name created response
func (o *UpdateSoftwareUpdateServerByNameCreated) Code() int {
	return 201
}

func (o *UpdateSoftwareUpdateServerByNameCreated) Error() string {
	return fmt.Sprintf("[PUT /softwareupdateservers/name/{name}][%d] updateSoftwareUpdateServerByNameCreated ", 201)
}

func (o *UpdateSoftwareUpdateServerByNameCreated) String() string {
	return fmt.Sprintf("[PUT /softwareupdateservers/name/{name}][%d] updateSoftwareUpdateServerByNameCreated ", 201)
}

func (o *UpdateSoftwareUpdateServerByNameCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
