// Code generated by go-swagger; DO NOT EDIT.

package mobiledevicehistory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindMobileDeviceHistoryBySerialNumberReader is a Reader for the FindMobileDeviceHistoryBySerialNumber structure.
type FindMobileDeviceHistoryBySerialNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindMobileDeviceHistoryBySerialNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindMobileDeviceHistoryBySerialNumberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /mobiledevicehistory/serialnumber/{serialnumber}] findMobileDeviceHistoryBySerialNumber", response, response.Code())
	}
}

// NewFindMobileDeviceHistoryBySerialNumberOK creates a FindMobileDeviceHistoryBySerialNumberOK with default headers values
func NewFindMobileDeviceHistoryBySerialNumberOK() *FindMobileDeviceHistoryBySerialNumberOK {
	return &FindMobileDeviceHistoryBySerialNumberOK{}
}

/*
FindMobileDeviceHistoryBySerialNumberOK describes a response with status code 200, with default header values.

OK
*/
type FindMobileDeviceHistoryBySerialNumberOK struct {
	Payload *models.MobileDeviceHistory
}

// IsSuccess returns true when this find mobile device history by serial number o k response has a 2xx status code
func (o *FindMobileDeviceHistoryBySerialNumberOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find mobile device history by serial number o k response has a 3xx status code
func (o *FindMobileDeviceHistoryBySerialNumberOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find mobile device history by serial number o k response has a 4xx status code
func (o *FindMobileDeviceHistoryBySerialNumberOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find mobile device history by serial number o k response has a 5xx status code
func (o *FindMobileDeviceHistoryBySerialNumberOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find mobile device history by serial number o k response a status code equal to that given
func (o *FindMobileDeviceHistoryBySerialNumberOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find mobile device history by serial number o k response
func (o *FindMobileDeviceHistoryBySerialNumberOK) Code() int {
	return 200
}

func (o *FindMobileDeviceHistoryBySerialNumberOK) Error() string {
	return fmt.Sprintf("[GET /mobiledevicehistory/serialnumber/{serialnumber}][%d] findMobileDeviceHistoryBySerialNumberOK  %+v", 200, o.Payload)
}

func (o *FindMobileDeviceHistoryBySerialNumberOK) String() string {
	return fmt.Sprintf("[GET /mobiledevicehistory/serialnumber/{serialnumber}][%d] findMobileDeviceHistoryBySerialNumberOK  %+v", 200, o.Payload)
}

func (o *FindMobileDeviceHistoryBySerialNumberOK) GetPayload() *models.MobileDeviceHistory {
	return o.Payload
}

func (o *FindMobileDeviceHistoryBySerialNumberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MobileDeviceHistory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
