// Code generated by go-swagger; DO NOT EDIT.

package mobiledevicehistory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindMobileDeviceHistoryByMacAddressSubsetParams creates a new FindMobileDeviceHistoryByMacAddressSubsetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindMobileDeviceHistoryByMacAddressSubsetParams() *FindMobileDeviceHistoryByMacAddressSubsetParams {
	return &FindMobileDeviceHistoryByMacAddressSubsetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindMobileDeviceHistoryByMacAddressSubsetParamsWithTimeout creates a new FindMobileDeviceHistoryByMacAddressSubsetParams object
// with the ability to set a timeout on a request.
func NewFindMobileDeviceHistoryByMacAddressSubsetParamsWithTimeout(timeout time.Duration) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	return &FindMobileDeviceHistoryByMacAddressSubsetParams{
		timeout: timeout,
	}
}

// NewFindMobileDeviceHistoryByMacAddressSubsetParamsWithContext creates a new FindMobileDeviceHistoryByMacAddressSubsetParams object
// with the ability to set a context for a request.
func NewFindMobileDeviceHistoryByMacAddressSubsetParamsWithContext(ctx context.Context) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	return &FindMobileDeviceHistoryByMacAddressSubsetParams{
		Context: ctx,
	}
}

// NewFindMobileDeviceHistoryByMacAddressSubsetParamsWithHTTPClient creates a new FindMobileDeviceHistoryByMacAddressSubsetParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindMobileDeviceHistoryByMacAddressSubsetParamsWithHTTPClient(client *http.Client) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	return &FindMobileDeviceHistoryByMacAddressSubsetParams{
		HTTPClient: client,
	}
}

/*
FindMobileDeviceHistoryByMacAddressSubsetParams contains all the parameters to send to the API endpoint

	for the find mobile device history by mac address subset operation.

	Typically these are written to a http.Request.
*/
type FindMobileDeviceHistoryByMacAddressSubsetParams struct {

	/* Macaddress.

	   Mac address to filter by
	*/
	Macaddress string

	/* Subset.

	   Subset to filter by
	*/
	Subset string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find mobile device history by mac address subset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) WithDefaults() *FindMobileDeviceHistoryByMacAddressSubsetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find mobile device history by mac address subset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) WithTimeout(timeout time.Duration) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) WithContext(ctx context.Context) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) WithHTTPClient(client *http.Client) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMacaddress adds the macaddress to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) WithMacaddress(macaddress string) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	o.SetMacaddress(macaddress)
	return o
}

// SetMacaddress adds the macaddress to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) SetMacaddress(macaddress string) {
	o.Macaddress = macaddress
}

// WithSubset adds the subset to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) WithSubset(subset string) *FindMobileDeviceHistoryByMacAddressSubsetParams {
	o.SetSubset(subset)
	return o
}

// SetSubset adds the subset to the find mobile device history by mac address subset params
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) SetSubset(subset string) {
	o.Subset = subset
}

// WriteToRequest writes these params to a swagger request
func (o *FindMobileDeviceHistoryByMacAddressSubsetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param macaddress
	if err := r.SetPathParam("macaddress", o.Macaddress); err != nil {
		return err
	}

	// path param subset
	if err := r.SetPathParam("subset", o.Subset); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
