// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateWebhookByNameParams creates a new UpdateWebhookByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateWebhookByNameParams() *UpdateWebhookByNameParams {
	return &UpdateWebhookByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateWebhookByNameParamsWithTimeout creates a new UpdateWebhookByNameParams object
// with the ability to set a timeout on a request.
func NewUpdateWebhookByNameParamsWithTimeout(timeout time.Duration) *UpdateWebhookByNameParams {
	return &UpdateWebhookByNameParams{
		timeout: timeout,
	}
}

// NewUpdateWebhookByNameParamsWithContext creates a new UpdateWebhookByNameParams object
// with the ability to set a context for a request.
func NewUpdateWebhookByNameParamsWithContext(ctx context.Context) *UpdateWebhookByNameParams {
	return &UpdateWebhookByNameParams{
		Context: ctx,
	}
}

// NewUpdateWebhookByNameParamsWithHTTPClient creates a new UpdateWebhookByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateWebhookByNameParamsWithHTTPClient(client *http.Client) *UpdateWebhookByNameParams {
	return &UpdateWebhookByNameParams{
		HTTPClient: client,
	}
}

/*
UpdateWebhookByNameParams contains all the parameters to send to the API endpoint

	for the update webhook by name operation.

	Typically these are written to a http.Request.
*/
type UpdateWebhookByNameParams struct {

	/* Name.

	   Name value to filter by
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update webhook by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateWebhookByNameParams) WithDefaults() *UpdateWebhookByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update webhook by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateWebhookByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update webhook by name params
func (o *UpdateWebhookByNameParams) WithTimeout(timeout time.Duration) *UpdateWebhookByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update webhook by name params
func (o *UpdateWebhookByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update webhook by name params
func (o *UpdateWebhookByNameParams) WithContext(ctx context.Context) *UpdateWebhookByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update webhook by name params
func (o *UpdateWebhookByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update webhook by name params
func (o *UpdateWebhookByNameParams) WithHTTPClient(client *http.Client) *UpdateWebhookByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update webhook by name params
func (o *UpdateWebhookByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the update webhook by name params
func (o *UpdateWebhookByNameParams) WithName(name string) *UpdateWebhookByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update webhook by name params
func (o *UpdateWebhookByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateWebhookByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
