// Code generated by go-swagger; DO NOT EDIT.

package scripts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateScriptByNameParams creates a new UpdateScriptByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateScriptByNameParams() *UpdateScriptByNameParams {
	return &UpdateScriptByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateScriptByNameParamsWithTimeout creates a new UpdateScriptByNameParams object
// with the ability to set a timeout on a request.
func NewUpdateScriptByNameParamsWithTimeout(timeout time.Duration) *UpdateScriptByNameParams {
	return &UpdateScriptByNameParams{
		timeout: timeout,
	}
}

// NewUpdateScriptByNameParamsWithContext creates a new UpdateScriptByNameParams object
// with the ability to set a context for a request.
func NewUpdateScriptByNameParamsWithContext(ctx context.Context) *UpdateScriptByNameParams {
	return &UpdateScriptByNameParams{
		Context: ctx,
	}
}

// NewUpdateScriptByNameParamsWithHTTPClient creates a new UpdateScriptByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateScriptByNameParamsWithHTTPClient(client *http.Client) *UpdateScriptByNameParams {
	return &UpdateScriptByNameParams{
		HTTPClient: client,
	}
}

/*
UpdateScriptByNameParams contains all the parameters to send to the API endpoint

	for the update script by name operation.

	Typically these are written to a http.Request.
*/
type UpdateScriptByNameParams struct {

	/* Name.

	   Name value to filter by
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update script by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateScriptByNameParams) WithDefaults() *UpdateScriptByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update script by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateScriptByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update script by name params
func (o *UpdateScriptByNameParams) WithTimeout(timeout time.Duration) *UpdateScriptByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update script by name params
func (o *UpdateScriptByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update script by name params
func (o *UpdateScriptByNameParams) WithContext(ctx context.Context) *UpdateScriptByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update script by name params
func (o *UpdateScriptByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update script by name params
func (o *UpdateScriptByNameParams) WithHTTPClient(client *http.Client) *UpdateScriptByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update script by name params
func (o *UpdateScriptByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the update script by name params
func (o *UpdateScriptByNameParams) WithName(name string) *UpdateScriptByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update script by name params
func (o *UpdateScriptByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateScriptByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
