// Code generated by go-swagger; DO NOT EDIT.

package buildings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindBuildingsByIDParams creates a new FindBuildingsByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindBuildingsByIDParams() *FindBuildingsByIDParams {
	return &FindBuildingsByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindBuildingsByIDParamsWithTimeout creates a new FindBuildingsByIDParams object
// with the ability to set a timeout on a request.
func NewFindBuildingsByIDParamsWithTimeout(timeout time.Duration) *FindBuildingsByIDParams {
	return &FindBuildingsByIDParams{
		timeout: timeout,
	}
}

// NewFindBuildingsByIDParamsWithContext creates a new FindBuildingsByIDParams object
// with the ability to set a context for a request.
func NewFindBuildingsByIDParamsWithContext(ctx context.Context) *FindBuildingsByIDParams {
	return &FindBuildingsByIDParams{
		Context: ctx,
	}
}

// NewFindBuildingsByIDParamsWithHTTPClient creates a new FindBuildingsByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindBuildingsByIDParamsWithHTTPClient(client *http.Client) *FindBuildingsByIDParams {
	return &FindBuildingsByIDParams{
		HTTPClient: client,
	}
}

/*
FindBuildingsByIDParams contains all the parameters to send to the API endpoint

	for the find buildings by Id operation.

	Typically these are written to a http.Request.
*/
type FindBuildingsByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find buildings by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindBuildingsByIDParams) WithDefaults() *FindBuildingsByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find buildings by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindBuildingsByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find buildings by Id params
func (o *FindBuildingsByIDParams) WithTimeout(timeout time.Duration) *FindBuildingsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find buildings by Id params
func (o *FindBuildingsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find buildings by Id params
func (o *FindBuildingsByIDParams) WithContext(ctx context.Context) *FindBuildingsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find buildings by Id params
func (o *FindBuildingsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find buildings by Id params
func (o *FindBuildingsByIDParams) WithHTTPClient(client *http.Client) *FindBuildingsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find buildings by Id params
func (o *FindBuildingsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find buildings by Id params
func (o *FindBuildingsByIDParams) WithID(id int64) *FindBuildingsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find buildings by Id params
func (o *FindBuildingsByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindBuildingsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
