script_opts = {
    "name": "",
    "info": "",
    "notes": "",
    "priority": "",
    "categoryId": "",
    "categoryName": "",
    "parameter4": "",
    "parameter5": "",
    "parameter6": "",
    "parameter7": "",
    "parameter8": "",
    "parameter9": "",
    "parameter10": "",
    "parameter11": "",
    "osRequirements": "",
    "scriptContents": "",
}

cache_opts = {
    "id": "",
    "name": "",
    "ehcacheMaxBytesLocalHeap": "",
    "elasticache": "bool",
    "cacheUniqueId": "",
    "timeToLiveSeconds": "int",
    "timeToIdleSeconds": "int",
    "cacheType": "ehcache",
}

computer_opts = {
    "udid": "123",
    "general": {
        "name": "Boalime",
        "lastIpAddress": "247.185.82.186",
        "lastReportedIp": "247.185.82.186",
        "jamfBinaryVersion": "9.27",
        "platform": "Mac",
        "barcode1": "5 12345 678900",
        "barcode2": "5 12345 678900",
        "assetTag": "304822",
        "remoteManagement": {"managed": True, "managementUsername": "rootname"},
        "supervised": True,
        "mdmCapable": {"capable": True, "capableUsers": ["admin", "rootadmin"]},
        "reportDate": "2018-10-31T18:04:13Z",
        "lastContactTime": "2018-10-31T18:04:13Z",
        "lastCloudBackupDate": "2018-10-31T18:04:13Z",
        "lastEnrolledDate": "2018-10-31T18:04:13Z",
        "mdmProfileExpiration": "2018-10-31T18:04:13Z",
        "initialEntryDate": "2018-10-31",
        "distributionPoint": "distribution point name",
        "enrollmentMethod": {},
        "site": {"id": "1", "name": "Eau Claire"},
        "itunesStoreAccountActive": True,
        "enrolledViaAutomatedDeviceEnrollment": True,
        "userApprovedMdm": True,
        "extensionAttributes": [{"definitionId": "23", "values": ["foo", "bar"]}],
    },
    "diskEncryption": {
        "bootPartitionEncryptionDetails": {
            "partitionName": "main",
            "partitionFileVault2State": "VALID",
            "partitionFileVault2Percent": 100,
        },
        "individualRecoveryKeyValidityStatus": "Valid",
        "institutionalRecoveryKeyPresent": True,
        "diskEncryptionConfigurationName": "Test configuration",
        "fileVault2EnabledUserNames": ["admin"],
        "fileVault2EligibilityMessage": "Not a boot partition",
    },
    "purchasing": {
        "leased": True,
        "purchased": True,
        "poNumber": "53-1",
        "poDate": "2019-01-01",
        "vendor": "Example Vendor",
        "warrantyDate": "2019-01-01",
        "appleCareId": "abcd",
        "leaseDate": "2019-01-01",
        "purchasePrice": "$500",
        "lifeExpectancy": 5,
        "purchasingAccount": "admin",
        "purchasingContact": "true",
        "extensionAttributes": [{"definitionId": "23", "values": ["foo", "bar"]}],
    },
    "applications": [
        {
            "name": "Microsoft Word",
            "path": "/usr/local/app",
            "version": "1.0.0",
            "macAppStore": True,
            "sizeMegabytes": 25,
            "bundleId": "1",
            "updateAvailable": False,
            "externalVersionId": "1",
        }
    ],
    "storage": {
        "disks": [
            {
                "partitions": [
                    {"fileVault2State": "VALID", "fileVault2ProgressPercent": 45}
                ]
            }
        ]
    },
    "userAndLocation": {
        "username": "Madison Anderson",
        "realname": "13-inch MacBook",
        "email": "email@com.pl",
        "position": "IT Team Lead",
        "phone": "123-456-789",
        "departmentId": "1",
        "buildingId": "1",
        "room": "5",
        "extensionAttributes": [{"definitionId": "23", "values": ["foo", "bar"]}],
    },
    "configurationProfiles": [{"lastInstalled": "2018-10-31T18:04:13Z"}],
    "printers": [
        {
            "name": "My Printer",
            "type": "XYZ 1122",
            "uri": "ipp://10.0.0.5",
            "location": "7th floor",
        }
    ],
    "services": [{"name": "SomeService"}],
    "hardware": {
        "networkAdapterType": "Foo",
        "macAddress": "6A:2C:4B:B7:65:B5",
        "altNetworkAdapterType": "Bar",
        "altMacAddress": "82:45:58:44:dc:01",
        "extensionAttributes": [{"definitionId": "23", "values": ["foo", "bar"]}],
    },
    "localUserAccounts": [
        {
            "uid": "501",
            "username": "jamf",
            "fullName": "John Jamf",
            "admin": True,
            "homeDirectory": "/Users/jamf",
            "fileVault2Enabled": True,
            "userAccountType": "LOCAL",
            "passwordMinLength": 4,
            "passwordMaxAge": 5,
            "passwordMinComplexCharacters": 5,
            "passwordHistoryDepth": 5,
            "passwordRequireAlphanumeric": True,
            "computerAzureActiveDirectoryId": "1",
            "userAzureActiveDirectoryId": "1",
            "azureActiveDirectoryId": "ACTIVATED",
        }
    ],
    "certificates": [
        {
            "commonName": "jamf.com",
            "identity": True,
            "expirationDate": "2030-10-31T18:04:13Z",
            "username": "test",
            "lifecycleStatus": "ACTIVE",
            "certificateStatus": "ISSUED",
        }
    ],
    "attachments": [
        {
            "id": "1",
            "name": "Attachment.pdf",
            "fileType": "application/pdf",
            "sizeBytes": 1024,
        }
    ],
    "plugins": [{"name": "plugin name", "version": "1.02", "path": "/Applications/"}],
    "packageReceipts": {
        "installedByJamfPro": ["com.jamf.protect.JamfProtect"],
        "installedByInstallerSwu": ["com.apple.pkg.Core"],
        "cached": ["com.jamf.protect.JamfProtect"],
    },
    "fonts": [{"name": "font name", "version": "1.02", "path": "/Applications/"}],
    "security": {
        "sipStatus": "ENABLED",
        "gatekeeperStatus": "APP_STORE_AND_IDENTIFIED_DEVELOPERS",
        "xprotectVersion": "1.2.3",
        "autoLoginDisabled": False,
        "remoteDesktopEnabled": True,
        "activationLockEnabled": True,
        "secureBootLevel": "FULL_SECURITY",
        "externalBootLevel": "ALLOW_BOOTING_FROM_EXTERNAL_MEDIA",
        "bootstrapTokenAllowed": True,
    },
    "operatingSystem": {
        "fileVault2Status": "ALL_ENCRYPTED",
        "extensionAttributes": [{"definitionId": "23", "values": ["foo", "bar"]}],
    },
    "licensedSoftware": [{"id": "1", "name": "Microsoft Word"}],
    "ibeacons": [{"name": "room A"}],
    "softwareUpdates": [
        {
            "name": "BEdit",
            "version": "1.15.2",
            "packageName": "com.apple.pkg.AdditionalEssentials",
        }
    ],
    "extensionAttributes": [{"definitionId": "23", "values": ["foo", "bar"]}],
    "contentCaching": {"dataMigrationError": {}},
    "groupMemberships": [{"groupId": "1", "groupName": "groupOne", "smartGroup": True}],
}

device_enrollment_opts = {
    "name": "Example Device Enrollment Instance",
    "supervisionIdentityId": "1",
    "siteId": "-1",
    "serverName": "string",
    "serverUuid": "string",
    "adminId": "string",
    "orgName": "string",
    "orgEmail": "string",
    "orgPhone": "string",
    "orgAddress": "string",
    "tokenExpirationDate": "string",
}

enrollment_opts = {
    "groupId": "1",
    "ldapServerId": "1",
    "name": "Grade School Pupils",
    "siteId": "-1",
    "enterpriseEnrollmentEnabled": True,
    "personalEnrollmentEnabled": True,
    "requireEula": True,
}

enrollment_language_opts = {
    "userEnrollmentText": "Enter your Managed Apple id to install the MDM Profile.",
    "userEnrollmentButton": "Continue",
    "userEnrollmentProfileName": "MDM Profile",
    "userEnrollmentProfileDescription": "MDM Profile for mobile device management",
    "quickAddName": "QuickAdd.pkg",
    "languageCode": "en",
    "name": "English",
    "title": "Enroll Your Device",
    "loginDescription": "Log in to enroll your device.",
    "username": "admin",
    "password": "12345",
    "loginButton": "Log in",
    "deviceClassDescription": "Specify if this device is institutionally owned or personally owned.",
    "deviceClassPersonal": "Personally Owned",
    "deviceClassPersonalDescription": "For personally owned devices, IT administrators **can**         *   Lock the device         *   Apply institutional settings         *   Install and remove institutional data         *   Install and remove institutional apps         For personally owned devices, IT administrators **cannot**         *   Wipe all data and settings from your device         *   Track the location of your device         *   Remove anything they did not install         *   Add/remove configuration profiles         *   Add/remove provisioning profiles",
    "deviceClassEnterprise": "Institutionally Owned",
    "deviceClassEnterpriseDescription": "For institutionally owned devices, IT administrators **can**         *   Wipe all data and settings from the device         *   Lock the device         *   Remove the passcode         *   Apply institutional settings         *   Install and remove institutional data         *   Install and remove institutional apps         *   Add/remove configuration profiles         *   Add/remove provisioning profiles         For institutionally owned devices, IT administrators **cannot**:         *   Remove anything they did not install",
    "deviceClassButton": "Enroll",
    "personalEula": "Personal Eula",
    "enterpriseEula": "Enterprise Eula",
    "eulaButton": "Accept",
    "siteDescription": "Select the site to use for enrolling this computer or mobile device.",
    "certificateText": "To continue with enrollment, you need to install the CA certificate for your organization.",
    "certificateButton": "Continue",
    "certificateProfileName": "CA Certificate",
    "certificateProfileDescription": "CA Certificate for mobile device management",
    "personalText": "To continue with enrollment, you need to install the MDM profile.",
    "personalButton": "Enroll",
    "personalProfileName": "MDM Profile",
    "personalProfileDescription": "MDM Profile for mobile device management",
    "enterpriseText": "To continue with enrollment, you need to install the MDM profile for your organization.",
    "enterpriseButton": "Continue",
    "enterpriseProfileName": "MDM Profile",
    "enterpriseProfileDescription": "MDM Profile for mobile device management",
    "enterprisePending": "To continue with enrollment, install the CA Certificate and MDM Profile that were downloaded to your computer.",
    "quickAddText": "Download and install this package.",
    "quickAddButton": "Download",
    "quickAddPending": "Install the downloaded QuickAdd.pkg.",
    "completeMessage": "The enrollment process is complete.",
    "failedMessage": "The enrollment process could not be completed. Contact your IT administrator.",
    "tryAgainButton": "Try Again",
    "checkNowButton": "Proceed",
    "checkEnrollmentMessage": 'Tap "Proceed" to view the enrollment status for this device.',
    "logoutButton": "Log Out",
}

enrollment_object_opts = {
    "installSingleProfile": True,
    "signingMdmProfileEnabled": False,
    "mdmSigningCertificate": {"filename": "null"},
    "restrictReenrollment": False,
    "flushLocationInformation": False,
    "flushLocationHistoryInformation": False,
    "flushPolicyHistory": False,
    "flushExtensionAttributes": False,
    "flushMdmCommandsOnReenroll": "DELETE_EVERYTHING_EXCEPT_ACKNOWLEDGED",
    "macOsEnterpriseEnrollmentEnabled": False,
    "managementPassword": "null",
    "passwordType": "STATIC",
    "randomPasswordLength": 8,
    "createManagementAccount": True,
    "hideManagementAccount": False,
    "allowSshOnlyManagementAccount": False,
    "ensureSshRunning": True,
    "launchSelfService": False,
    "signQuickAdd": False,
    "developerCertificateIdentity": {"filename": "null"},
    "iosEnterpriseEnrollmentEnabled": True,
    "iosPersonalEnrollmentEnabled": False,
    "personalDeviceEnrollmentType": "PERSONALDEVICEPROFILES",
}

enrollent_panel_opts = {
    "ldapGroupAccess": [{"ldapServerId": 1, "groupName": "admins"}],
    "displayName": "A Panel",
    "rank": 0,
    "usernameLabel": "Username",
    "passwordLabel": "Password",
    "title": "My Ldap Panel",
    "backButtonText": "Back",
    "continueButtonText": "Continue",
}

jamf_connect_opts = {
    "uuid": "string",
    "profileId": "string",
    "profileName": "string",
    "profileScopeDescription": "string",
    "version": "2.3.0",
    "autoDeploymentType": [
        "NONE",
        "PATCH_UPDATES",
        "MINOR_AND_PATCH_UPDATES",
        "INITIAL_INSTALLATION_ONLY",
    ],
}

prestage_opts = {
    "displayName": "string",
    "isMandatory": True,
    "isMdmRemovable": True,
    "supportPhoneNumber": "string",
    "supportEmailAddress": "string",
    "department": "string",
    "isDefaultPrestage": True,
    "enrollmentSiteId": 0,
    "isKeepExistingSiteMembership": True,
    "isKeepExistingLocationInformation": True,
    "isRequireAuthentication": True,
    "authenticationPrompt": "string",
    "isPreventActivationLock": True,
    "isEnableDeviceBasedActivationLock": True,
    "deviceEnrollmentProgramInstanceId": 0,
    "skipSetupItems": {"additionalProp": True},
    "locationInformation": {
        "username": "string",
        "realname": "string",
        "phone": "string",
        "email": "string",
        "room": "string",
        "position": "string",
        "departmentId": 0,
        "buildingId": 0,
        "id": 0,
        "versionLock": 0,
    },
    "purchasingInformation": {
        "id": 0,
        "isLeased": True,
        "isPurchased": True,
        "appleCareID": "string",
        "poNumber": "string",
        "vendor": "string",
        "purchasePrice": "string",
        "lifeExpectancy": 0,
        "purchasingAccount": "string",
        "purchasingContact": "string",
        "leaseDate": "string",
        "poDate": "string",
        "warrantyDate": "string",
        "versionLock": 0,
    },
    "anchorCertificates": ["string"],
    "enrollmentCustomizationId": 0,
    "isInstallProfilesDuringSetup": True,
    "prestageInstalledProfileIds": [0],
    "customPackageIds": [0],
    "customPackageDistributionPointId": 0,
    "id": 0,
    "profileUUID": "string",
    "siteId": 0,
    "versionLock": 0,
}

mobile_opts = {
    "id": 0,
    "name": "string",
    "assetTag": "string",
    "lastInventoryUpdateTimestamp": "2021-08-06T14:29:36.021Z",
    "osVersion": "string",
    "osBuild": "string",
    "serialNumber": "string",
    "udid": "string",
    "ipAddress": "string",
    "wifiMacAddress": "string",
    "bluetoothMacAddress": "string",
    "isManaged": True,
    "initialEntryTimestamp": "2021-08-06T14:29:36.021Z",
    "lastEnrollmentTimestamp": "2021-08-06T14:29:36.021Z",
    "deviceOwnershipLevel": "string",
    "site": {"name": "string", "id": 0},
    "extensionAttributes": [
        {
            "id": 0,
            "name": "string",
            "type": "STRING",
            "value": ["string"],
            "isExtensionAttributeCollectionAllowed": True,
        }
    ],
    "location": {
        "username": "string",
        "realName": "string",
        "emailAddress": "string",
        "position": "string",
        "phoneNumber": "string",
        "department": {"name": "string", "id": 0},
        "building": {"name": "string", "id": 0},
        "room": "string",
    },
    "type": "ios",
    "ios": {
        "model": "string",
        "modelIdentifier": "string",
        "modelNumber": "string",
        "isSupervised": True,
        "batteryLevel": 0,
        "lastBackupTimestamp": "2021-08-06T14:29:36.021Z",
        "capacityMb": 0,
        "availableMb": 0,
        "percentageUsed": 0,
        "isShared": True,
        "isDeviceLocatorServiceEnabled": True,
        "isDoNotDisturbEnabled": True,
        "isCloudBackupEnabled": True,
        "lastCloudBackupTimestamp": "2021-08-06T14:29:36.021Z",
        "isLocationServicesEnabled": True,
        "isITunesStoreAccountActive": True,
        "isBleCapable": True,
        "computer": {"name": "string", "id": 0},
        "purchasing": {
            "isPurchased": True,
            "isLeased": True,
            "poNumber": "string",
            "vendor": "string",
            "appleCareId": "string",
            "purchasePrice": "string",
            "purchasingAccount": "string",
            "poDate": "2021-08-06T14:29:36.022Z",
            "warrantyExpiresDate": "2021-08-06T14:29:36.022Z",
            "leaseExpiresDate": "2021-08-06T14:29:36.022Z",
            "lifeExpectancy": 0,
            "purchasingContact": "string",
        },
        "security": {
            "isDataProtected": True,
            "isBlockLevelEncryptionCapable": True,
            "isFileLevelEncryptionCapable": True,
            "isPasscodePresent": True,
            "isPasscodeCompliant": True,
            "isPasscodeCompliantWithProfile": True,
            "hardwareEncryption": 0,
            "isActivationLockEnabled": True,
            "isJailBreakDetected": True,
        },
        "network": {
            "cellularTechnology": "string",
            "isVoiceRoamingEnabled": True,
            "imei": "string",
            "iccid": "string",
            "meid": "string",
            "carrierSettingsVersion": "string",
            "currentCarrierNetwork": "string",
            "currentMobileCountryCode": "string",
            "currentMobileNetworkCode": "string",
            "homeCarrierNetwork": "string",
            "homeMobileCountryCode": "string",
            "homeMobileNetworkCode": "string",
            "isDataRoamingEnabled": True,
            "isRoaming": True,
            "isPersonalHotspotEnabled": True,
            "phoneNumber": "string",
        },
        "applications": [
            {
                "identifier": "string",
                "name": "string",
                "version": "string",
                "short,Version": "string",
            }
        ],
        "certificates": [{"commonName": "string", "isIdentity": True}],
        "ebooks": [{"author": "string", "title": "string", "version": "string"}],
        "configurationProfiles": [
            {
                "displayName": "string",
                "version": "string",
                "uuid": "string",
                "identifier": "string",
            }
        ],
        "provisioningProfiles": [
            {
                "displayName": "string",
                "uuid": "string",
                "expirationDate": "2021-08-06T14:29:36.022Z",
            }
        ],
        "attachments": [{"name": "string", "id": 0}],
    },
    "appleTv": {
        "model": "string",
        "modelIdentifier": "string",
        "modelNumber": "string",
        "isSupervised": True,
        "airplayPassword": "string",
        "deviceId": "string",
        "locales": "string",
        "purchasing": {
            "isPurchased": True,
            "isLeased": True,
            "poNumber": "string",
            "vendor": "string",
            "appleCareId": "string",
            "purchasePrice": "string",
            "purchasingAccount": "string",
            "poDate": "2021-08-06T14:29:36.022Z",
            "warrantyExpiresDate": "2021-08-06T14:29:36.022Z",
            "leaseExpiresDate": "2021-08-06T14:29:36.022Z",
            "lifeExpectancy": 0,
            "purchasingContact": "string",
        },
        "configurationProfiles": [
            {
                "displayName": "string",
                "version": "string",
                "uuid": "string",
                "identifier": "string",
            }
        ],
    },
    "android": {
        "osName": "string",
        "manufacturer": "string",
        "model": "string",
        "internalCapacityMb": 0,
        "internalAvailableMb": 0,
        "internalPercentUsed": 0,
        "externalCapacityMb": 0,
        "externalAvailableMb": 0,
        "externalPercentUsed": 0,
        "batteryLevel": 0,
        "lastBackupTimestamp": "2021-08-06T14:29:36.022Z",
        "apiVersion": 0,
        "computer": {"name": "string", "id": 0},
        "security": {
            "isDataProtected": True,
            "isBlockLevelEncryptionCapable": True,
            "isFileLevelEncryptionCapable": True,
            "isPasscodePresent": True,
            "isPasscodeCompliant": True,
            "isPasscodeCompliantWithProfile": True,
            "hardwareEncryption": 0,
            "isActivationLockEnabled": True,
            "isJailBreakDetected": True,
        },
    },
}


mobile_search_opts = {
    "orderBy": [{"field": "Name"}],
    "pageNumber": 1,
    "pageSize": 100,
    "isLoadToEnd": True,
    "udid": "2b6f0cc904d137be2e1730235f5664094b831186",
    "macAddress": "ee:00:7c:f0:e5:aa",
    "name": "Jan's MObile Device",
    "serialNumber": "C02L29ECF8J1",
    "osType": "IOS",
    "isManaged": True,
}

patch_report_opts = {
    "softwareTitleID": 1,
    "title": "Patch title",
    "latestVersion": "2",
    "releaseDate": "2018-10-15T16:39:56.307Z",
    "upToDate": 3,
    "outOfDate": 6,
    "isOnDashboard": True,
    "softwareTitleConfigurationID": 1,
}

mdm_command_opts = {
    "manifest": {
        "url": "https://example.jamf.com/this/package",
        "hash": "dcb02a41cd6d842943459a88c96a5f72",
        "displayImageUrl": "https://example.jamf.com/img/display/this/package.jpg",
        "bundleId": "com.jamf.example",
        "bundleVersion": "0.1.0",
        "subtitle": "Subtitle",
        "title": "Title",
        "sizeInBytes": 12345,
    },
    "devices": [1, 2, 3],
    "installAsManaged": True,
    "groupId": "1",
}

notification_opts = [
    "APNS_CERT_REVOKED",
    "APNS_CONNECTION_FAILURE",
    "APPLE_SCHOOL_MANAGER_T_C_NOT_SIGNED",
    "BUILT_IN_CA_EXPIRED",
    "BUILT_IN_CA_EXPIRING",
    "BUILT_IN_CA_RENEWAL_FAILED",
    "BUILT_IN_CA_RENEWAL_SUCCESS",
    "CLOUD_LDAP_CERT_EXPIRED",
    "CLOUD_LDAP_CERT_WILL_EXPIRE",
    "COMPUTER_SECURITY_SSL_DISABLED",
    "DEP_INSTANCE_EXPIRED",
    "DEP_INSTANCE_WILL_EXPIRE",
    "DEVICE_ENROLLMENT_PROGRAM_T_C_NOT_SIGNED",
    "EXCEEDED_LICENSE_COUNT",
    "FREQUENT_INVENTORY_COLLECTION_POLICY",
    "GSX_CERT_EXPIRED",
    "GSX_CERT_WILL_EXPIRE",
    "HCL_BIND_ERROR",
    "HCL_ERROR",
    "INSECURE_LDAP",
    "INVALID_REFERENCES_EXT_ATTR",
    "INVALID_REFERENCES_POLICIES",
    "INVALID_REFERENCES_SCRIPTS",
    "JAMF_CONNECT_UPDATE",
    "JAMF_PROTECT_UPDATE",
    "JIM_ERROR",
    "LDAP_CONNECTION_CHECK_THROUGH_JIM_FAILED",
    "LDAP_CONNECTION_CHECK_THROUGH_JIM_SUCCESSFUL",
    "MDM_EXTERNAL_SIGNING_CERTIFICATE_EXPIRED",
    "MDM_EXTERNAL_SIGNING_CERTIFICATE_EXPIRING",
    "MDM_EXTERNAL_SIGNING_CERTIFICATE_EXPIRING_TODAY",
    "MII_HEARTBEAT_FAILED_NOTIFICATION",
    "MII_INVENTORY_UPLOAD_FAILED_NOTIFICATION",
    "MII_UNATHORIZED_RESPONSE_NOTIFICATION",
    "PATCH_EXTENTION_ATTRIBUTE",
    "PATCH_UPDATE",
    "POLICY_MANAGEMENT_ACCOUNT_PAYLOAD_SECURITY_MULTIPLE",
    "POLICY_MANAGEMENT_ACCOUNT_PAYLOAD_SECURITY_SINGLE",
    "PRESTAGE_IMAGING_SECURITY",
    "PUSH_CERT_EXPIRED",
    "PUSH_CERT_WILL_EXPIRE",
    "PUSH_PROXY_CERT_EXPIRED",
    "SSO_CERT_EXPIRED",
    "SSO_CERT_WILL_EXPIRE",
    "TOMCAT_SSL_CERT_EXPIRED",
    "TOMCAT_SSL_CERT_WILL_EXPIRE",
    "USER_INITIATED_ENROLLMENT_MANAGEMENT_ACCOUNT_SECURITY_ISSUE",
    "USER_MAID_DUPLICATE_ERROR",
    "USER_MAID_MISMATCH_ERROR",
    "USER_MAID_ROSTER_DUPLICATE_ERROR",
    "VPP_ACCOUNT_EXPIRED",
    "VPP_ACCOUNT_WILL_EXPIRE",
    "VPP_TOKEN_REVOKED",
    "DEVICE_COMPLIANCE_CONNECTION_ERROR",
    "CONDITIONAL_ACCESS_CONNECTION_ERROR",
]

self_service_branding_opts = {
    "id": 1,
    "name": "Test iOS Branding",
    "operatingSystem": "IOS",
    "brandingName": "My Self Service",
    "iconUrl": "http://jamfUrl/icon/1",
    "headerBackgroundColorCode": "0000FF",
    "menuIconColorCode": "0000FF",
    "brandingNameColorCode": "0000FF",
    "statusBarTextColor": "dark",
}

self_service_object_opts = {
    "installSettings": {
        "installAutomatically": True,
        "installLocation": "/Applications",
    },
    "loginSettings": {"allowRememberMe": True, "authType": "Basic"},
    "configurationSettings": {
        "notificationsEnabled": True,
        "alertUserApprovedMdm": True,
        "defaultLandingPage": "HOME",
        "defaultHomeCategoryId": -1,
        "bookmarksName": "Bookmarks",
    },
}
