// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindPoliciesByCategoryParams creates a new FindPoliciesByCategoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindPoliciesByCategoryParams() *FindPoliciesByCategoryParams {
	return &FindPoliciesByCategoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindPoliciesByCategoryParamsWithTimeout creates a new FindPoliciesByCategoryParams object
// with the ability to set a timeout on a request.
func NewFindPoliciesByCategoryParamsWithTimeout(timeout time.Duration) *FindPoliciesByCategoryParams {
	return &FindPoliciesByCategoryParams{
		timeout: timeout,
	}
}

// NewFindPoliciesByCategoryParamsWithContext creates a new FindPoliciesByCategoryParams object
// with the ability to set a context for a request.
func NewFindPoliciesByCategoryParamsWithContext(ctx context.Context) *FindPoliciesByCategoryParams {
	return &FindPoliciesByCategoryParams{
		Context: ctx,
	}
}

// NewFindPoliciesByCategoryParamsWithHTTPClient creates a new FindPoliciesByCategoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindPoliciesByCategoryParamsWithHTTPClient(client *http.Client) *FindPoliciesByCategoryParams {
	return &FindPoliciesByCategoryParams{
		HTTPClient: client,
	}
}

/*
FindPoliciesByCategoryParams contains all the parameters to send to the API endpoint

	for the find policies by category operation.

	Typically these are written to a http.Request.
*/
type FindPoliciesByCategoryParams struct {

	/* Category.

	   Category to filter by
	*/
	Category string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find policies by category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindPoliciesByCategoryParams) WithDefaults() *FindPoliciesByCategoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find policies by category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindPoliciesByCategoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find policies by category params
func (o *FindPoliciesByCategoryParams) WithTimeout(timeout time.Duration) *FindPoliciesByCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find policies by category params
func (o *FindPoliciesByCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find policies by category params
func (o *FindPoliciesByCategoryParams) WithContext(ctx context.Context) *FindPoliciesByCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find policies by category params
func (o *FindPoliciesByCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find policies by category params
func (o *FindPoliciesByCategoryParams) WithHTTPClient(client *http.Client) *FindPoliciesByCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find policies by category params
func (o *FindPoliciesByCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the find policies by category params
func (o *FindPoliciesByCategoryParams) WithCategory(category string) *FindPoliciesByCategoryParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the find policies by category params
func (o *FindPoliciesByCategoryParams) SetCategory(category string) {
	o.Category = category
}

// WriteToRequest writes these params to a swagger request
func (o *FindPoliciesByCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param category
	if err := r.SetPathParam("category", o.Category); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
