// Code generated by go-swagger; DO NOT EDIT.

package healthcarelistenerrule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindHealthcareListenerRulesByIDParams creates a new FindHealthcareListenerRulesByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindHealthcareListenerRulesByIDParams() *FindHealthcareListenerRulesByIDParams {
	return &FindHealthcareListenerRulesByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindHealthcareListenerRulesByIDParamsWithTimeout creates a new FindHealthcareListenerRulesByIDParams object
// with the ability to set a timeout on a request.
func NewFindHealthcareListenerRulesByIDParamsWithTimeout(timeout time.Duration) *FindHealthcareListenerRulesByIDParams {
	return &FindHealthcareListenerRulesByIDParams{
		timeout: timeout,
	}
}

// NewFindHealthcareListenerRulesByIDParamsWithContext creates a new FindHealthcareListenerRulesByIDParams object
// with the ability to set a context for a request.
func NewFindHealthcareListenerRulesByIDParamsWithContext(ctx context.Context) *FindHealthcareListenerRulesByIDParams {
	return &FindHealthcareListenerRulesByIDParams{
		Context: ctx,
	}
}

// NewFindHealthcareListenerRulesByIDParamsWithHTTPClient creates a new FindHealthcareListenerRulesByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindHealthcareListenerRulesByIDParamsWithHTTPClient(client *http.Client) *FindHealthcareListenerRulesByIDParams {
	return &FindHealthcareListenerRulesByIDParams{
		HTTPClient: client,
	}
}

/*
FindHealthcareListenerRulesByIDParams contains all the parameters to send to the API endpoint

	for the find healthcare listener rules by Id operation.

	Typically these are written to a http.Request.
*/
type FindHealthcareListenerRulesByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find healthcare listener rules by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindHealthcareListenerRulesByIDParams) WithDefaults() *FindHealthcareListenerRulesByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find healthcare listener rules by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindHealthcareListenerRulesByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) WithTimeout(timeout time.Duration) *FindHealthcareListenerRulesByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) WithContext(ctx context.Context) *FindHealthcareListenerRulesByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) WithHTTPClient(client *http.Client) *FindHealthcareListenerRulesByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) WithID(id string) *FindHealthcareListenerRulesByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find healthcare listener rules by Id params
func (o *FindHealthcareListenerRulesByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindHealthcareListenerRulesByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
