// Code generated by go-swagger; DO NOT EDIT.

package computerapplications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindComputerApplicationByNameAndVersionReader is a Reader for the FindComputerApplicationByNameAndVersion structure.
type FindComputerApplicationByNameAndVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindComputerApplicationByNameAndVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindComputerApplicationByNameAndVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /computerapplications/application/{application}/version/{version}] findComputerApplicationByNameAndVersion", response, response.Code())
	}
}

// NewFindComputerApplicationByNameAndVersionOK creates a FindComputerApplicationByNameAndVersionOK with default headers values
func NewFindComputerApplicationByNameAndVersionOK() *FindComputerApplicationByNameAndVersionOK {
	return &FindComputerApplicationByNameAndVersionOK{}
}

/*
FindComputerApplicationByNameAndVersionOK describes a response with status code 200, with default header values.

OK
*/
type FindComputerApplicationByNameAndVersionOK struct {
	Payload *models.ComputerApplications
}

// IsSuccess returns true when this find computer application by name and version o k response has a 2xx status code
func (o *FindComputerApplicationByNameAndVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find computer application by name and version o k response has a 3xx status code
func (o *FindComputerApplicationByNameAndVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find computer application by name and version o k response has a 4xx status code
func (o *FindComputerApplicationByNameAndVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find computer application by name and version o k response has a 5xx status code
func (o *FindComputerApplicationByNameAndVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find computer application by name and version o k response a status code equal to that given
func (o *FindComputerApplicationByNameAndVersionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find computer application by name and version o k response
func (o *FindComputerApplicationByNameAndVersionOK) Code() int {
	return 200
}

func (o *FindComputerApplicationByNameAndVersionOK) Error() string {
	return fmt.Sprintf("[GET /computerapplications/application/{application}/version/{version}][%d] findComputerApplicationByNameAndVersionOK  %+v", 200, o.Payload)
}

func (o *FindComputerApplicationByNameAndVersionOK) String() string {
	return fmt.Sprintf("[GET /computerapplications/application/{application}/version/{version}][%d] findComputerApplicationByNameAndVersionOK  %+v", 200, o.Payload)
}

func (o *FindComputerApplicationByNameAndVersionOK) GetPayload() *models.ComputerApplications {
	return o.Payload
}

func (o *FindComputerApplicationByNameAndVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComputerApplications)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
