// Code generated by go-swagger; DO NOT EDIT.

package restrictedsoftware

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindRestrictedSoftwareByNameReader is a Reader for the FindRestrictedSoftwareByName structure.
type FindRestrictedSoftwareByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindRestrictedSoftwareByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindRestrictedSoftwareByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /restrictedsoftware/name/{name}] findRestrictedSoftwareByName", response, response.Code())
	}
}

// NewFindRestrictedSoftwareByNameOK creates a FindRestrictedSoftwareByNameOK with default headers values
func NewFindRestrictedSoftwareByNameOK() *FindRestrictedSoftwareByNameOK {
	return &FindRestrictedSoftwareByNameOK{}
}

/*
FindRestrictedSoftwareByNameOK describes a response with status code 200, with default header values.

OK
*/
type FindRestrictedSoftwareByNameOK struct {
	Payload *models.RestrictedSoftware
}

// IsSuccess returns true when this find restricted software by name o k response has a 2xx status code
func (o *FindRestrictedSoftwareByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find restricted software by name o k response has a 3xx status code
func (o *FindRestrictedSoftwareByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find restricted software by name o k response has a 4xx status code
func (o *FindRestrictedSoftwareByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find restricted software by name o k response has a 5xx status code
func (o *FindRestrictedSoftwareByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find restricted software by name o k response a status code equal to that given
func (o *FindRestrictedSoftwareByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find restricted software by name o k response
func (o *FindRestrictedSoftwareByNameOK) Code() int {
	return 200
}

func (o *FindRestrictedSoftwareByNameOK) Error() string {
	return fmt.Sprintf("[GET /restrictedsoftware/name/{name}][%d] findRestrictedSoftwareByNameOK  %+v", 200, o.Payload)
}

func (o *FindRestrictedSoftwareByNameOK) String() string {
	return fmt.Sprintf("[GET /restrictedsoftware/name/{name}][%d] findRestrictedSoftwareByNameOK  %+v", 200, o.Payload)
}

func (o *FindRestrictedSoftwareByNameOK) GetPayload() *models.RestrictedSoftware {
	return o.Payload
}

func (o *FindRestrictedSoftwareByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RestrictedSoftware)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
