// Code generated by go-swagger; DO NOT EDIT.

package computerhistory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindComputerHistoryByIDSubsetParams creates a new FindComputerHistoryByIDSubsetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindComputerHistoryByIDSubsetParams() *FindComputerHistoryByIDSubsetParams {
	return &FindComputerHistoryByIDSubsetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindComputerHistoryByIDSubsetParamsWithTimeout creates a new FindComputerHistoryByIDSubsetParams object
// with the ability to set a timeout on a request.
func NewFindComputerHistoryByIDSubsetParamsWithTimeout(timeout time.Duration) *FindComputerHistoryByIDSubsetParams {
	return &FindComputerHistoryByIDSubsetParams{
		timeout: timeout,
	}
}

// NewFindComputerHistoryByIDSubsetParamsWithContext creates a new FindComputerHistoryByIDSubsetParams object
// with the ability to set a context for a request.
func NewFindComputerHistoryByIDSubsetParamsWithContext(ctx context.Context) *FindComputerHistoryByIDSubsetParams {
	return &FindComputerHistoryByIDSubsetParams{
		Context: ctx,
	}
}

// NewFindComputerHistoryByIDSubsetParamsWithHTTPClient creates a new FindComputerHistoryByIDSubsetParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindComputerHistoryByIDSubsetParamsWithHTTPClient(client *http.Client) *FindComputerHistoryByIDSubsetParams {
	return &FindComputerHistoryByIDSubsetParams{
		HTTPClient: client,
	}
}

/*
FindComputerHistoryByIDSubsetParams contains all the parameters to send to the API endpoint

	for the find computer history by Id subset operation.

	Typically these are written to a http.Request.
*/
type FindComputerHistoryByIDSubsetParams struct {

	/* ID.

	   Computer ID to filter by
	*/
	ID int64

	/* Subset.

	   Subset to filter by
	*/
	Subset string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find computer history by Id subset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindComputerHistoryByIDSubsetParams) WithDefaults() *FindComputerHistoryByIDSubsetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find computer history by Id subset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindComputerHistoryByIDSubsetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) WithTimeout(timeout time.Duration) *FindComputerHistoryByIDSubsetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) WithContext(ctx context.Context) *FindComputerHistoryByIDSubsetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) WithHTTPClient(client *http.Client) *FindComputerHistoryByIDSubsetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) WithID(id int64) *FindComputerHistoryByIDSubsetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) SetID(id int64) {
	o.ID = id
}

// WithSubset adds the subset to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) WithSubset(subset string) *FindComputerHistoryByIDSubsetParams {
	o.SetSubset(subset)
	return o
}

// SetSubset adds the subset to the find computer history by Id subset params
func (o *FindComputerHistoryByIDSubsetParams) SetSubset(subset string) {
	o.Subset = subset
}

// WriteToRequest writes these params to a swagger request
func (o *FindComputerHistoryByIDSubsetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param subset
	if err := r.SetPathParam("subset", o.Subset); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
