// Code generated by go-swagger; DO NOT EDIT.

package mobiledeviceextensionattributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteMobiledeviceextensionattributeByIDParams creates a new DeleteMobiledeviceextensionattributeByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMobiledeviceextensionattributeByIDParams() *DeleteMobiledeviceextensionattributeByIDParams {
	return &DeleteMobiledeviceextensionattributeByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMobiledeviceextensionattributeByIDParamsWithTimeout creates a new DeleteMobiledeviceextensionattributeByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteMobiledeviceextensionattributeByIDParamsWithTimeout(timeout time.Duration) *DeleteMobiledeviceextensionattributeByIDParams {
	return &DeleteMobiledeviceextensionattributeByIDParams{
		timeout: timeout,
	}
}

// NewDeleteMobiledeviceextensionattributeByIDParamsWithContext creates a new DeleteMobiledeviceextensionattributeByIDParams object
// with the ability to set a context for a request.
func NewDeleteMobiledeviceextensionattributeByIDParamsWithContext(ctx context.Context) *DeleteMobiledeviceextensionattributeByIDParams {
	return &DeleteMobiledeviceextensionattributeByIDParams{
		Context: ctx,
	}
}

// NewDeleteMobiledeviceextensionattributeByIDParamsWithHTTPClient creates a new DeleteMobiledeviceextensionattributeByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMobiledeviceextensionattributeByIDParamsWithHTTPClient(client *http.Client) *DeleteMobiledeviceextensionattributeByIDParams {
	return &DeleteMobiledeviceextensionattributeByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteMobiledeviceextensionattributeByIDParams contains all the parameters to send to the API endpoint

	for the delete mobiledeviceextensionattribute by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteMobiledeviceextensionattributeByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete mobiledeviceextensionattribute by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMobiledeviceextensionattributeByIDParams) WithDefaults() *DeleteMobiledeviceextensionattributeByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete mobiledeviceextensionattribute by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMobiledeviceextensionattributeByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) WithTimeout(timeout time.Duration) *DeleteMobiledeviceextensionattributeByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) WithContext(ctx context.Context) *DeleteMobiledeviceextensionattributeByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) WithHTTPClient(client *http.Client) *DeleteMobiledeviceextensionattributeByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) WithID(id int64) *DeleteMobiledeviceextensionattributeByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete mobiledeviceextensionattribute by Id params
func (o *DeleteMobiledeviceextensionattributeByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMobiledeviceextensionattributeByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
