// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MobileDeviceInvitations mobile device invitations
//
// swagger:model mobile_device_invitations
type MobileDeviceInvitations []*MobileDeviceInvitationsItems0

// Validate validates this mobile device invitations
func (m MobileDeviceInvitations) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this mobile device invitations based on the context it is used
func (m MobileDeviceInvitations) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if m[i] != nil {

			if swag.IsZero(m[i]) { // not required
				return nil
			}

			if err := m[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MobileDeviceInvitationsItems0 mobile device invitations items0
//
// swagger:model MobileDeviceInvitationsItems0
type MobileDeviceInvitationsItems0 struct {

	// mobile device invitation
	MobileDeviceInvitation *MobileDeviceInvitationsItems0MobileDeviceInvitation `json:"mobile_device_invitation,omitempty"`

	// size
	Size Size `json:"size,omitempty"`
}

// Validate validates this mobile device invitations items0
func (m *MobileDeviceInvitationsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMobileDeviceInvitation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MobileDeviceInvitationsItems0) validateMobileDeviceInvitation(formats strfmt.Registry) error {
	if swag.IsZero(m.MobileDeviceInvitation) { // not required
		return nil
	}

	if m.MobileDeviceInvitation != nil {
		if err := m.MobileDeviceInvitation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mobile_device_invitation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("mobile_device_invitation")
			}
			return err
		}
	}

	return nil
}

func (m *MobileDeviceInvitationsItems0) validateSize(formats strfmt.Registry) error {
	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if err := m.Size.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("size")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("size")
		}
		return err
	}

	return nil
}

// ContextValidate validate this mobile device invitations items0 based on the context it is used
func (m *MobileDeviceInvitationsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMobileDeviceInvitation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSize(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MobileDeviceInvitationsItems0) contextValidateMobileDeviceInvitation(ctx context.Context, formats strfmt.Registry) error {

	if m.MobileDeviceInvitation != nil {

		if swag.IsZero(m.MobileDeviceInvitation) { // not required
			return nil
		}

		if err := m.MobileDeviceInvitation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mobile_device_invitation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("mobile_device_invitation")
			}
			return err
		}
	}

	return nil
}

func (m *MobileDeviceInvitationsItems0) contextValidateSize(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if err := m.Size.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("size")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("size")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MobileDeviceInvitationsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MobileDeviceInvitationsItems0) UnmarshalBinary(b []byte) error {
	var res MobileDeviceInvitationsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// MobileDeviceInvitationsItems0MobileDeviceInvitation mobile device invitations items0 mobile device invitation
//
// swagger:model MobileDeviceInvitationsItems0MobileDeviceInvitation
type MobileDeviceInvitationsItems0MobileDeviceInvitation struct {

	// expiration date
	// Example: 2012-05-07 11:13:35
	ExpirationDate string `json:"expiration_date,omitempty"`

	// expiration date epoch
	// Example: 1336407215609
	ExpirationDateEpoch int64 `json:"expiration_date_epoch,omitempty"`

	// expiration date utc
	// Example: 2012-05-07T11:13:35.609-0500
	ExpirationDateUtc string `json:"expiration_date_utc,omitempty"`

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// invitation
	// Example: 7.249663721735319e+37
	Invitation int64 `json:"invitation,omitempty"`

	// invitation type
	// Example: USER_INITATIED_EMAIL
	InvitationType string `json:"invitation_type,omitempty"`

	// last action
	// Example: NONE
	LastAction string `json:"last_action,omitempty"`
}

// Validate validates this mobile device invitations items0 mobile device invitation
func (m *MobileDeviceInvitationsItems0MobileDeviceInvitation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this mobile device invitations items0 mobile device invitation based on context it is used
func (m *MobileDeviceInvitationsItems0MobileDeviceInvitation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MobileDeviceInvitationsItems0MobileDeviceInvitation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MobileDeviceInvitationsItems0MobileDeviceInvitation) UnmarshalBinary(b []byte) error {
	var res MobileDeviceInvitationsItems0MobileDeviceInvitation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
