// Code generated by go-swagger; DO NOT EDIT.

package printers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindPrintersByIDReader is a Reader for the FindPrintersByID structure.
type FindPrintersByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindPrintersByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindPrintersByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /printers/id/{id}] findPrintersById", response, response.Code())
	}
}

// NewFindPrintersByIDOK creates a FindPrintersByIDOK with default headers values
func NewFindPrintersByIDOK() *FindPrintersByIDOK {
	return &FindPrintersByIDOK{}
}

/*
FindPrintersByIDOK describes a response with status code 200, with default header values.

OK
*/
type FindPrintersByIDOK struct {
	Payload *models.Printer
}

// IsSuccess returns true when this find printers by Id o k response has a 2xx status code
func (o *FindPrintersByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find printers by Id o k response has a 3xx status code
func (o *FindPrintersByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find printers by Id o k response has a 4xx status code
func (o *FindPrintersByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find printers by Id o k response has a 5xx status code
func (o *FindPrintersByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find printers by Id o k response a status code equal to that given
func (o *FindPrintersByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find printers by Id o k response
func (o *FindPrintersByIDOK) Code() int {
	return 200
}

func (o *FindPrintersByIDOK) Error() string {
	return fmt.Sprintf("[GET /printers/id/{id}][%d] findPrintersByIdOK  %+v", 200, o.Payload)
}

func (o *FindPrintersByIDOK) String() string {
	return fmt.Sprintf("[GET /printers/id/{id}][%d] findPrintersByIdOK  %+v", 200, o.Payload)
}

func (o *FindPrintersByIDOK) GetPayload() *models.Printer {
	return o.Payload
}

func (o *FindPrintersByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Printer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
