// Code generated by go-swagger; DO NOT EDIT.

package advancedusersearches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdateAdvancedUserSearchByIDParams creates a new UpdateAdvancedUserSearchByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateAdvancedUserSearchByIDParams() *UpdateAdvancedUserSearchByIDParams {
	return &UpdateAdvancedUserSearchByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAdvancedUserSearchByIDParamsWithTimeout creates a new UpdateAdvancedUserSearchByIDParams object
// with the ability to set a timeout on a request.
func NewUpdateAdvancedUserSearchByIDParamsWithTimeout(timeout time.Duration) *UpdateAdvancedUserSearchByIDParams {
	return &UpdateAdvancedUserSearchByIDParams{
		timeout: timeout,
	}
}

// NewUpdateAdvancedUserSearchByIDParamsWithContext creates a new UpdateAdvancedUserSearchByIDParams object
// with the ability to set a context for a request.
func NewUpdateAdvancedUserSearchByIDParamsWithContext(ctx context.Context) *UpdateAdvancedUserSearchByIDParams {
	return &UpdateAdvancedUserSearchByIDParams{
		Context: ctx,
	}
}

// NewUpdateAdvancedUserSearchByIDParamsWithHTTPClient creates a new UpdateAdvancedUserSearchByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateAdvancedUserSearchByIDParamsWithHTTPClient(client *http.Client) *UpdateAdvancedUserSearchByIDParams {
	return &UpdateAdvancedUserSearchByIDParams{
		HTTPClient: client,
	}
}

/*
UpdateAdvancedUserSearchByIDParams contains all the parameters to send to the API endpoint

	for the update advanced user search by Id operation.

	Typically these are written to a http.Request.
*/
type UpdateAdvancedUserSearchByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update advanced user search by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAdvancedUserSearchByIDParams) WithDefaults() *UpdateAdvancedUserSearchByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update advanced user search by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAdvancedUserSearchByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) WithTimeout(timeout time.Duration) *UpdateAdvancedUserSearchByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) WithContext(ctx context.Context) *UpdateAdvancedUserSearchByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) WithHTTPClient(client *http.Client) *UpdateAdvancedUserSearchByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) WithID(id int64) *UpdateAdvancedUserSearchByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update advanced user search by Id params
func (o *UpdateAdvancedUserSearchByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAdvancedUserSearchByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
