// Code generated by go-swagger; DO NOT EDIT.

package departments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdateDepartmentByIDParams creates a new UpdateDepartmentByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDepartmentByIDParams() *UpdateDepartmentByIDParams {
	return &UpdateDepartmentByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDepartmentByIDParamsWithTimeout creates a new UpdateDepartmentByIDParams object
// with the ability to set a timeout on a request.
func NewUpdateDepartmentByIDParamsWithTimeout(timeout time.Duration) *UpdateDepartmentByIDParams {
	return &UpdateDepartmentByIDParams{
		timeout: timeout,
	}
}

// NewUpdateDepartmentByIDParamsWithContext creates a new UpdateDepartmentByIDParams object
// with the ability to set a context for a request.
func NewUpdateDepartmentByIDParamsWithContext(ctx context.Context) *UpdateDepartmentByIDParams {
	return &UpdateDepartmentByIDParams{
		Context: ctx,
	}
}

// NewUpdateDepartmentByIDParamsWithHTTPClient creates a new UpdateDepartmentByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDepartmentByIDParamsWithHTTPClient(client *http.Client) *UpdateDepartmentByIDParams {
	return &UpdateDepartmentByIDParams{
		HTTPClient: client,
	}
}

/*
UpdateDepartmentByIDParams contains all the parameters to send to the API endpoint

	for the update department by Id operation.

	Typically these are written to a http.Request.
*/
type UpdateDepartmentByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update department by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDepartmentByIDParams) WithDefaults() *UpdateDepartmentByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update department by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDepartmentByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update department by Id params
func (o *UpdateDepartmentByIDParams) WithTimeout(timeout time.Duration) *UpdateDepartmentByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update department by Id params
func (o *UpdateDepartmentByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update department by Id params
func (o *UpdateDepartmentByIDParams) WithContext(ctx context.Context) *UpdateDepartmentByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update department by Id params
func (o *UpdateDepartmentByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update department by Id params
func (o *UpdateDepartmentByIDParams) WithHTTPClient(client *http.Client) *UpdateDepartmentByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update department by Id params
func (o *UpdateDepartmentByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update department by Id params
func (o *UpdateDepartmentByIDParams) WithID(id int64) *UpdateDepartmentByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update department by Id params
func (o *UpdateDepartmentByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDepartmentByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
