// Code generated by go-swagger; DO NOT EDIT.

package computergroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteComputerGroupByNameParams creates a new DeleteComputerGroupByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteComputerGroupByNameParams() *DeleteComputerGroupByNameParams {
	return &DeleteComputerGroupByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteComputerGroupByNameParamsWithTimeout creates a new DeleteComputerGroupByNameParams object
// with the ability to set a timeout on a request.
func NewDeleteComputerGroupByNameParamsWithTimeout(timeout time.Duration) *DeleteComputerGroupByNameParams {
	return &DeleteComputerGroupByNameParams{
		timeout: timeout,
	}
}

// NewDeleteComputerGroupByNameParamsWithContext creates a new DeleteComputerGroupByNameParams object
// with the ability to set a context for a request.
func NewDeleteComputerGroupByNameParamsWithContext(ctx context.Context) *DeleteComputerGroupByNameParams {
	return &DeleteComputerGroupByNameParams{
		Context: ctx,
	}
}

// NewDeleteComputerGroupByNameParamsWithHTTPClient creates a new DeleteComputerGroupByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteComputerGroupByNameParamsWithHTTPClient(client *http.Client) *DeleteComputerGroupByNameParams {
	return &DeleteComputerGroupByNameParams{
		HTTPClient: client,
	}
}

/*
DeleteComputerGroupByNameParams contains all the parameters to send to the API endpoint

	for the delete computer group by name operation.

	Typically these are written to a http.Request.
*/
type DeleteComputerGroupByNameParams struct {

	/* Name.

	   Name value to filter by
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete computer group by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComputerGroupByNameParams) WithDefaults() *DeleteComputerGroupByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete computer group by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComputerGroupByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) WithTimeout(timeout time.Duration) *DeleteComputerGroupByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) WithContext(ctx context.Context) *DeleteComputerGroupByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) WithHTTPClient(client *http.Client) *DeleteComputerGroupByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) WithName(name string) *DeleteComputerGroupByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete computer group by name params
func (o *DeleteComputerGroupByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteComputerGroupByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
