// Code generated by go-swagger; DO NOT EDIT.

package diskencryptionconfigurations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindDiskEncryptionConfigurationsByIDReader is a Reader for the FindDiskEncryptionConfigurationsByID structure.
type FindDiskEncryptionConfigurationsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindDiskEncryptionConfigurationsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindDiskEncryptionConfigurationsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /diskencryptionconfigurations/id/{id}] findDiskEncryptionConfigurationsById", response, response.Code())
	}
}

// NewFindDiskEncryptionConfigurationsByIDOK creates a FindDiskEncryptionConfigurationsByIDOK with default headers values
func NewFindDiskEncryptionConfigurationsByIDOK() *FindDiskEncryptionConfigurationsByIDOK {
	return &FindDiskEncryptionConfigurationsByIDOK{}
}

/*
FindDiskEncryptionConfigurationsByIDOK describes a response with status code 200, with default header values.

OK
*/
type FindDiskEncryptionConfigurationsByIDOK struct {
	Payload *models.DiskEncryptionConfiguration
}

// IsSuccess returns true when this find disk encryption configurations by Id o k response has a 2xx status code
func (o *FindDiskEncryptionConfigurationsByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find disk encryption configurations by Id o k response has a 3xx status code
func (o *FindDiskEncryptionConfigurationsByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find disk encryption configurations by Id o k response has a 4xx status code
func (o *FindDiskEncryptionConfigurationsByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find disk encryption configurations by Id o k response has a 5xx status code
func (o *FindDiskEncryptionConfigurationsByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find disk encryption configurations by Id o k response a status code equal to that given
func (o *FindDiskEncryptionConfigurationsByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find disk encryption configurations by Id o k response
func (o *FindDiskEncryptionConfigurationsByIDOK) Code() int {
	return 200
}

func (o *FindDiskEncryptionConfigurationsByIDOK) Error() string {
	return fmt.Sprintf("[GET /diskencryptionconfigurations/id/{id}][%d] findDiskEncryptionConfigurationsByIdOK  %+v", 200, o.Payload)
}

func (o *FindDiskEncryptionConfigurationsByIDOK) String() string {
	return fmt.Sprintf("[GET /diskencryptionconfigurations/id/{id}][%d] findDiskEncryptionConfigurationsByIdOK  %+v", 200, o.Payload)
}

func (o *FindDiskEncryptionConfigurationsByIDOK) GetPayload() *models.DiskEncryptionConfiguration {
	return o.Payload
}

func (o *FindDiskEncryptionConfigurationsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DiskEncryptionConfiguration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
