// Code generated by go-swagger; DO NOT EDIT.

package diskencryptionconfigurations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateDiskEncryptionConfigurationByNameReader is a Reader for the UpdateDiskEncryptionConfigurationByName structure.
type UpdateDiskEncryptionConfigurationByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDiskEncryptionConfigurationByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateDiskEncryptionConfigurationByNameCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /diskencryptionconfigurations/name/{name}] updateDiskEncryptionConfigurationByName", response, response.Code())
	}
}

// NewUpdateDiskEncryptionConfigurationByNameCreated creates a UpdateDiskEncryptionConfigurationByNameCreated with default headers values
func NewUpdateDiskEncryptionConfigurationByNameCreated() *UpdateDiskEncryptionConfigurationByNameCreated {
	return &UpdateDiskEncryptionConfigurationByNameCreated{}
}

/*
UpdateDiskEncryptionConfigurationByNameCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateDiskEncryptionConfigurationByNameCreated struct {
}

// IsSuccess returns true when this update disk encryption configuration by name created response has a 2xx status code
func (o *UpdateDiskEncryptionConfigurationByNameCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update disk encryption configuration by name created response has a 3xx status code
func (o *UpdateDiskEncryptionConfigurationByNameCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update disk encryption configuration by name created response has a 4xx status code
func (o *UpdateDiskEncryptionConfigurationByNameCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update disk encryption configuration by name created response has a 5xx status code
func (o *UpdateDiskEncryptionConfigurationByNameCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update disk encryption configuration by name created response a status code equal to that given
func (o *UpdateDiskEncryptionConfigurationByNameCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update disk encryption configuration by name created response
func (o *UpdateDiskEncryptionConfigurationByNameCreated) Code() int {
	return 201
}

func (o *UpdateDiskEncryptionConfigurationByNameCreated) Error() string {
	return fmt.Sprintf("[PUT /diskencryptionconfigurations/name/{name}][%d] updateDiskEncryptionConfigurationByNameCreated ", 201)
}

func (o *UpdateDiskEncryptionConfigurationByNameCreated) String() string {
	return fmt.Sprintf("[PUT /diskencryptionconfigurations/name/{name}][%d] updateDiskEncryptionConfigurationByNameCreated ", 201)
}

func (o *UpdateDiskEncryptionConfigurationByNameCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
