// Code generated by go-swagger; DO NOT EDIT.

package ebooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindEBooksByNameSubsetParams creates a new FindEBooksByNameSubsetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindEBooksByNameSubsetParams() *FindEBooksByNameSubsetParams {
	return &FindEBooksByNameSubsetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindEBooksByNameSubsetParamsWithTimeout creates a new FindEBooksByNameSubsetParams object
// with the ability to set a timeout on a request.
func NewFindEBooksByNameSubsetParamsWithTimeout(timeout time.Duration) *FindEBooksByNameSubsetParams {
	return &FindEBooksByNameSubsetParams{
		timeout: timeout,
	}
}

// NewFindEBooksByNameSubsetParamsWithContext creates a new FindEBooksByNameSubsetParams object
// with the ability to set a context for a request.
func NewFindEBooksByNameSubsetParamsWithContext(ctx context.Context) *FindEBooksByNameSubsetParams {
	return &FindEBooksByNameSubsetParams{
		Context: ctx,
	}
}

// NewFindEBooksByNameSubsetParamsWithHTTPClient creates a new FindEBooksByNameSubsetParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindEBooksByNameSubsetParamsWithHTTPClient(client *http.Client) *FindEBooksByNameSubsetParams {
	return &FindEBooksByNameSubsetParams{
		HTTPClient: client,
	}
}

/*
FindEBooksByNameSubsetParams contains all the parameters to send to the API endpoint

	for the find e books by name subset operation.

	Typically these are written to a http.Request.
*/
type FindEBooksByNameSubsetParams struct {

	/* Name.

	   Name to filter by
	*/
	Name string

	/* Subset.

	   Subset to filter by
	*/
	Subset string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find e books by name subset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindEBooksByNameSubsetParams) WithDefaults() *FindEBooksByNameSubsetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find e books by name subset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindEBooksByNameSubsetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) WithTimeout(timeout time.Duration) *FindEBooksByNameSubsetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) WithContext(ctx context.Context) *FindEBooksByNameSubsetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) WithHTTPClient(client *http.Client) *FindEBooksByNameSubsetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) WithName(name string) *FindEBooksByNameSubsetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) SetName(name string) {
	o.Name = name
}

// WithSubset adds the subset to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) WithSubset(subset string) *FindEBooksByNameSubsetParams {
	o.SetSubset(subset)
	return o
}

// SetSubset adds the subset to the find e books by name subset params
func (o *FindEBooksByNameSubsetParams) SetSubset(subset string) {
	o.Subset = subset
}

// WriteToRequest writes these params to a swagger request
func (o *FindEBooksByNameSubsetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param subset
	if err := r.SetPathParam("subset", o.Subset); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
