// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAccountByNameReader is a Reader for the DeleteAccountByName structure.
type DeleteAccountByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccountByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAccountByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /accounts/username/{name}] deleteAccountByName", response, response.Code())
	}
}

// NewDeleteAccountByNameOK creates a DeleteAccountByNameOK with default headers values
func NewDeleteAccountByNameOK() *DeleteAccountByNameOK {
	return &DeleteAccountByNameOK{}
}

/*
DeleteAccountByNameOK describes a response with status code 200, with default header values.

OK
*/
type DeleteAccountByNameOK struct {
}

// IsSuccess returns true when this delete account by name o k response has a 2xx status code
func (o *DeleteAccountByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete account by name o k response has a 3xx status code
func (o *DeleteAccountByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete account by name o k response has a 4xx status code
func (o *DeleteAccountByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete account by name o k response has a 5xx status code
func (o *DeleteAccountByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete account by name o k response a status code equal to that given
func (o *DeleteAccountByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete account by name o k response
func (o *DeleteAccountByNameOK) Code() int {
	return 200
}

func (o *DeleteAccountByNameOK) Error() string {
	return fmt.Sprintf("[DELETE /accounts/username/{name}][%d] deleteAccountByNameOK ", 200)
}

func (o *DeleteAccountByNameOK) String() string {
	return fmt.Sprintf("[DELETE /accounts/username/{name}][%d] deleteAccountByNameOK ", 200)
}

func (o *DeleteAccountByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
