// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteGroupByIDReader is a Reader for the DeleteGroupByID structure.
type DeleteGroupByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGroupByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteGroupByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /accounts/groupid/{id}] deleteGroupById", response, response.Code())
	}
}

// NewDeleteGroupByIDOK creates a DeleteGroupByIDOK with default headers values
func NewDeleteGroupByIDOK() *DeleteGroupByIDOK {
	return &DeleteGroupByIDOK{}
}

/*
DeleteGroupByIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteGroupByIDOK struct {
}

// IsSuccess returns true when this delete group by Id o k response has a 2xx status code
func (o *DeleteGroupByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete group by Id o k response has a 3xx status code
func (o *DeleteGroupByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete group by Id o k response has a 4xx status code
func (o *DeleteGroupByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete group by Id o k response has a 5xx status code
func (o *DeleteGroupByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete group by Id o k response a status code equal to that given
func (o *DeleteGroupByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete group by Id o k response
func (o *DeleteGroupByIDOK) Code() int {
	return 200
}

func (o *DeleteGroupByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /accounts/groupid/{id}][%d] deleteGroupByIdOK ", 200)
}

func (o *DeleteGroupByIDOK) String() string {
	return fmt.Sprintf("[DELETE /accounts/groupid/{id}][%d] deleteGroupByIdOK ", 200)
}

func (o *DeleteGroupByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
