// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteGroupByNameReader is a Reader for the DeleteGroupByName structure.
type DeleteGroupByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGroupByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteGroupByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /accounts/groupname/{name}] deleteGroupByName", response, response.Code())
	}
}

// NewDeleteGroupByNameOK creates a DeleteGroupByNameOK with default headers values
func NewDeleteGroupByNameOK() *DeleteGroupByNameOK {
	return &DeleteGroupByNameOK{}
}

/*
DeleteGroupByNameOK describes a response with status code 200, with default header values.

OK
*/
type DeleteGroupByNameOK struct {
}

// IsSuccess returns true when this delete group by name o k response has a 2xx status code
func (o *DeleteGroupByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete group by name o k response has a 3xx status code
func (o *DeleteGroupByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete group by name o k response has a 4xx status code
func (o *DeleteGroupByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete group by name o k response has a 5xx status code
func (o *DeleteGroupByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete group by name o k response a status code equal to that given
func (o *DeleteGroupByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete group by name o k response
func (o *DeleteGroupByNameOK) Code() int {
	return 200
}

func (o *DeleteGroupByNameOK) Error() string {
	return fmt.Sprintf("[DELETE /accounts/groupname/{name}][%d] deleteGroupByNameOK ", 200)
}

func (o *DeleteGroupByNameOK) String() string {
	return fmt.Sprintf("[DELETE /accounts/groupname/{name}][%d] deleteGroupByNameOK ", 200)
}

func (o *DeleteGroupByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
