// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindAccountsByIDReader is a Reader for the FindAccountsByID structure.
type FindAccountsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindAccountsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindAccountsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /accounts/userid/{id}] findAccountsById", response, response.Code())
	}
}

// NewFindAccountsByIDOK creates a FindAccountsByIDOK with default headers values
func NewFindAccountsByIDOK() *FindAccountsByIDOK {
	return &FindAccountsByIDOK{}
}

/*
FindAccountsByIDOK describes a response with status code 200, with default header values.

OK
*/
type FindAccountsByIDOK struct {
	Payload *models.Account
}

// IsSuccess returns true when this find accounts by Id o k response has a 2xx status code
func (o *FindAccountsByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find accounts by Id o k response has a 3xx status code
func (o *FindAccountsByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find accounts by Id o k response has a 4xx status code
func (o *FindAccountsByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find accounts by Id o k response has a 5xx status code
func (o *FindAccountsByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find accounts by Id o k response a status code equal to that given
func (o *FindAccountsByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find accounts by Id o k response
func (o *FindAccountsByIDOK) Code() int {
	return 200
}

func (o *FindAccountsByIDOK) Error() string {
	return fmt.Sprintf("[GET /accounts/userid/{id}][%d] findAccountsByIdOK  %+v", 200, o.Payload)
}

func (o *FindAccountsByIDOK) String() string {
	return fmt.Sprintf("[GET /accounts/userid/{id}][%d] findAccountsByIdOK  %+v", 200, o.Payload)
}

func (o *FindAccountsByIDOK) GetPayload() *models.Account {
	return o.Payload
}

func (o *FindAccountsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Account)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
