// Code generated by go-swagger; DO NOT EDIT.

package userextensionattributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindUserextensionattributesByNameReader is a Reader for the FindUserextensionattributesByName structure.
type FindUserextensionattributesByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindUserextensionattributesByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindUserextensionattributesByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /userextensionattributes/name/{name}] findUserextensionattributesByName", response, response.Code())
	}
}

// NewFindUserextensionattributesByNameOK creates a FindUserextensionattributesByNameOK with default headers values
func NewFindUserextensionattributesByNameOK() *FindUserextensionattributesByNameOK {
	return &FindUserextensionattributesByNameOK{}
}

/*
FindUserextensionattributesByNameOK describes a response with status code 200, with default header values.

OK
*/
type FindUserextensionattributesByNameOK struct {
	Payload *models.UserExtensionAttribute
}

// IsSuccess returns true when this find userextensionattributes by name o k response has a 2xx status code
func (o *FindUserextensionattributesByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find userextensionattributes by name o k response has a 3xx status code
func (o *FindUserextensionattributesByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find userextensionattributes by name o k response has a 4xx status code
func (o *FindUserextensionattributesByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find userextensionattributes by name o k response has a 5xx status code
func (o *FindUserextensionattributesByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find userextensionattributes by name o k response a status code equal to that given
func (o *FindUserextensionattributesByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find userextensionattributes by name o k response
func (o *FindUserextensionattributesByNameOK) Code() int {
	return 200
}

func (o *FindUserextensionattributesByNameOK) Error() string {
	return fmt.Sprintf("[GET /userextensionattributes/name/{name}][%d] findUserextensionattributesByNameOK  %+v", 200, o.Payload)
}

func (o *FindUserextensionattributesByNameOK) String() string {
	return fmt.Sprintf("[GET /userextensionattributes/name/{name}][%d] findUserextensionattributesByNameOK  %+v", 200, o.Payload)
}

func (o *FindUserextensionattributesByNameOK) GetPayload() *models.UserExtensionAttribute {
	return o.Payload
}

func (o *FindUserextensionattributesByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserExtensionAttribute)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
