// Code generated by go-swagger; DO NOT EDIT.

package byoprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteBYOProfilesByIDReader is a Reader for the DeleteBYOProfilesByID structure.
type DeleteBYOProfilesByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBYOProfilesByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteBYOProfilesByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /byoprofiles/id/{id}] deleteBYOProfilesById", response, response.Code())
	}
}

// NewDeleteBYOProfilesByIDOK creates a DeleteBYOProfilesByIDOK with default headers values
func NewDeleteBYOProfilesByIDOK() *DeleteBYOProfilesByIDOK {
	return &DeleteBYOProfilesByIDOK{}
}

/*
DeleteBYOProfilesByIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteBYOProfilesByIDOK struct {
}

// IsSuccess returns true when this delete b y o profiles by Id o k response has a 2xx status code
func (o *DeleteBYOProfilesByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete b y o profiles by Id o k response has a 3xx status code
func (o *DeleteBYOProfilesByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete b y o profiles by Id o k response has a 4xx status code
func (o *DeleteBYOProfilesByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete b y o profiles by Id o k response has a 5xx status code
func (o *DeleteBYOProfilesByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete b y o profiles by Id o k response a status code equal to that given
func (o *DeleteBYOProfilesByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete b y o profiles by Id o k response
func (o *DeleteBYOProfilesByIDOK) Code() int {
	return 200
}

func (o *DeleteBYOProfilesByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /byoprofiles/id/{id}][%d] deleteBYOProfilesByIdOK ", 200)
}

func (o *DeleteBYOProfilesByIDOK) String() string {
	return fmt.Sprintf("[DELETE /byoprofiles/id/{id}][%d] deleteBYOProfilesByIdOK ", 200)
}

func (o *DeleteBYOProfilesByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
