// Code generated by go-swagger; DO NOT EDIT.

package byoprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindBYOProfilesByNameReader is a Reader for the FindBYOProfilesByName structure.
type FindBYOProfilesByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindBYOProfilesByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindBYOProfilesByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /byoprofiles/name/{name}] findBYOProfilesByName", response, response.Code())
	}
}

// NewFindBYOProfilesByNameOK creates a FindBYOProfilesByNameOK with default headers values
func NewFindBYOProfilesByNameOK() *FindBYOProfilesByNameOK {
	return &FindBYOProfilesByNameOK{}
}

/*
FindBYOProfilesByNameOK describes a response with status code 200, with default header values.

OK
*/
type FindBYOProfilesByNameOK struct {
	Payload *models.Byoprofile
}

// IsSuccess returns true when this find b y o profiles by name o k response has a 2xx status code
func (o *FindBYOProfilesByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find b y o profiles by name o k response has a 3xx status code
func (o *FindBYOProfilesByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find b y o profiles by name o k response has a 4xx status code
func (o *FindBYOProfilesByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find b y o profiles by name o k response has a 5xx status code
func (o *FindBYOProfilesByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find b y o profiles by name o k response a status code equal to that given
func (o *FindBYOProfilesByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find b y o profiles by name o k response
func (o *FindBYOProfilesByNameOK) Code() int {
	return 200
}

func (o *FindBYOProfilesByNameOK) Error() string {
	return fmt.Sprintf("[GET /byoprofiles/name/{name}][%d] findBYOProfilesByNameOK  %+v", 200, o.Payload)
}

func (o *FindBYOProfilesByNameOK) String() string {
	return fmt.Sprintf("[GET /byoprofiles/name/{name}][%d] findBYOProfilesByNameOK  %+v", 200, o.Payload)
}

func (o *FindBYOProfilesByNameOK) GetPayload() *models.Byoprofile {
	return o.Payload
}

func (o *FindBYOProfilesByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Byoprofile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
