// Code generated by go-swagger; DO NOT EDIT.

package computercheckin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateComputerCheckinReader is a Reader for the UpdateComputerCheckin structure.
type UpdateComputerCheckinReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateComputerCheckinReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateComputerCheckinCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /computercheckin] updateComputerCheckin", response, response.Code())
	}
}

// NewUpdateComputerCheckinCreated creates a UpdateComputerCheckinCreated with default headers values
func NewUpdateComputerCheckinCreated() *UpdateComputerCheckinCreated {
	return &UpdateComputerCheckinCreated{}
}

/*
UpdateComputerCheckinCreated describes a response with status code 201, with default header values.

Created
*/
type UpdateComputerCheckinCreated struct {
}

// IsSuccess returns true when this update computer checkin created response has a 2xx status code
func (o *UpdateComputerCheckinCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update computer checkin created response has a 3xx status code
func (o *UpdateComputerCheckinCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update computer checkin created response has a 4xx status code
func (o *UpdateComputerCheckinCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this update computer checkin created response has a 5xx status code
func (o *UpdateComputerCheckinCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this update computer checkin created response a status code equal to that given
func (o *UpdateComputerCheckinCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the update computer checkin created response
func (o *UpdateComputerCheckinCreated) Code() int {
	return 201
}

func (o *UpdateComputerCheckinCreated) Error() string {
	return fmt.Sprintf("[PUT /computercheckin][%d] updateComputerCheckinCreated ", 201)
}

func (o *UpdateComputerCheckinCreated) String() string {
	return fmt.Sprintf("[PUT /computercheckin][%d] updateComputerCheckinCreated ", 201)
}

func (o *UpdateComputerCheckinCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
