// Code generated by go-swagger; DO NOT EDIT.

package computers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateComputerByIDParams creates a new CreateComputerByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateComputerByIDParams() *CreateComputerByIDParams {
	return &CreateComputerByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateComputerByIDParamsWithTimeout creates a new CreateComputerByIDParams object
// with the ability to set a timeout on a request.
func NewCreateComputerByIDParamsWithTimeout(timeout time.Duration) *CreateComputerByIDParams {
	return &CreateComputerByIDParams{
		timeout: timeout,
	}
}

// NewCreateComputerByIDParamsWithContext creates a new CreateComputerByIDParams object
// with the ability to set a context for a request.
func NewCreateComputerByIDParamsWithContext(ctx context.Context) *CreateComputerByIDParams {
	return &CreateComputerByIDParams{
		Context: ctx,
	}
}

// NewCreateComputerByIDParamsWithHTTPClient creates a new CreateComputerByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateComputerByIDParamsWithHTTPClient(client *http.Client) *CreateComputerByIDParams {
	return &CreateComputerByIDParams{
		HTTPClient: client,
	}
}

/*
CreateComputerByIDParams contains all the parameters to send to the API endpoint

	for the create computer by Id operation.

	Typically these are written to a http.Request.
*/
type CreateComputerByIDParams struct {

	/* ID.

	   ID value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create computer by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateComputerByIDParams) WithDefaults() *CreateComputerByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create computer by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateComputerByIDParams) SetDefaults() {
	var (
		idDefault = int64(0)
	)

	val := CreateComputerByIDParams{
		ID: idDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create computer by Id params
func (o *CreateComputerByIDParams) WithTimeout(timeout time.Duration) *CreateComputerByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create computer by Id params
func (o *CreateComputerByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create computer by Id params
func (o *CreateComputerByIDParams) WithContext(ctx context.Context) *CreateComputerByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create computer by Id params
func (o *CreateComputerByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create computer by Id params
func (o *CreateComputerByIDParams) WithHTTPClient(client *http.Client) *CreateComputerByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create computer by Id params
func (o *CreateComputerByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create computer by Id params
func (o *CreateComputerByIDParams) WithID(id int64) *CreateComputerByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create computer by Id params
func (o *CreateComputerByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateComputerByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
