// Code generated by go-swagger; DO NOT EDIT.

package computers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteComputerByMacAddressParams creates a new DeleteComputerByMacAddressParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteComputerByMacAddressParams() *DeleteComputerByMacAddressParams {
	return &DeleteComputerByMacAddressParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteComputerByMacAddressParamsWithTimeout creates a new DeleteComputerByMacAddressParams object
// with the ability to set a timeout on a request.
func NewDeleteComputerByMacAddressParamsWithTimeout(timeout time.Duration) *DeleteComputerByMacAddressParams {
	return &DeleteComputerByMacAddressParams{
		timeout: timeout,
	}
}

// NewDeleteComputerByMacAddressParamsWithContext creates a new DeleteComputerByMacAddressParams object
// with the ability to set a context for a request.
func NewDeleteComputerByMacAddressParamsWithContext(ctx context.Context) *DeleteComputerByMacAddressParams {
	return &DeleteComputerByMacAddressParams{
		Context: ctx,
	}
}

// NewDeleteComputerByMacAddressParamsWithHTTPClient creates a new DeleteComputerByMacAddressParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteComputerByMacAddressParamsWithHTTPClient(client *http.Client) *DeleteComputerByMacAddressParams {
	return &DeleteComputerByMacAddressParams{
		HTTPClient: client,
	}
}

/*
DeleteComputerByMacAddressParams contains all the parameters to send to the API endpoint

	for the delete computer by mac address operation.

	Typically these are written to a http.Request.
*/
type DeleteComputerByMacAddressParams struct {

	/* Macaddress.

	   MAC address value to filter by
	*/
	Macaddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete computer by mac address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComputerByMacAddressParams) WithDefaults() *DeleteComputerByMacAddressParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete computer by mac address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComputerByMacAddressParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) WithTimeout(timeout time.Duration) *DeleteComputerByMacAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) WithContext(ctx context.Context) *DeleteComputerByMacAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) WithHTTPClient(client *http.Client) *DeleteComputerByMacAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMacaddress adds the macaddress to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) WithMacaddress(macaddress string) *DeleteComputerByMacAddressParams {
	o.SetMacaddress(macaddress)
	return o
}

// SetMacaddress adds the macaddress to the delete computer by mac address params
func (o *DeleteComputerByMacAddressParams) SetMacaddress(macaddress string) {
	o.Macaddress = macaddress
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteComputerByMacAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param macaddress
	if err := r.SetPathParam("macaddress", o.Macaddress); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
