// Code generated by go-swagger; DO NOT EDIT.

package computers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteComputerByUDIDParams creates a new DeleteComputerByUDIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteComputerByUDIDParams() *DeleteComputerByUDIDParams {
	return &DeleteComputerByUDIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteComputerByUDIDParamsWithTimeout creates a new DeleteComputerByUDIDParams object
// with the ability to set a timeout on a request.
func NewDeleteComputerByUDIDParamsWithTimeout(timeout time.Duration) *DeleteComputerByUDIDParams {
	return &DeleteComputerByUDIDParams{
		timeout: timeout,
	}
}

// NewDeleteComputerByUDIDParamsWithContext creates a new DeleteComputerByUDIDParams object
// with the ability to set a context for a request.
func NewDeleteComputerByUDIDParamsWithContext(ctx context.Context) *DeleteComputerByUDIDParams {
	return &DeleteComputerByUDIDParams{
		Context: ctx,
	}
}

// NewDeleteComputerByUDIDParamsWithHTTPClient creates a new DeleteComputerByUDIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteComputerByUDIDParamsWithHTTPClient(client *http.Client) *DeleteComputerByUDIDParams {
	return &DeleteComputerByUDIDParams{
		HTTPClient: client,
	}
}

/*
DeleteComputerByUDIDParams contains all the parameters to send to the API endpoint

	for the delete computer by u d ID operation.

	Typically these are written to a http.Request.
*/
type DeleteComputerByUDIDParams struct {

	/* Udid.

	   UDID value to filter by
	*/
	Udid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete computer by u d ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComputerByUDIDParams) WithDefaults() *DeleteComputerByUDIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete computer by u d ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteComputerByUDIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) WithTimeout(timeout time.Duration) *DeleteComputerByUDIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) WithContext(ctx context.Context) *DeleteComputerByUDIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) WithHTTPClient(client *http.Client) *DeleteComputerByUDIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUdid adds the udid to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) WithUdid(udid string) *DeleteComputerByUDIDParams {
	o.SetUdid(udid)
	return o
}

// SetUdid adds the udid to the delete computer by u d ID params
func (o *DeleteComputerByUDIDParams) SetUdid(udid string) {
	o.Udid = udid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteComputerByUDIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param udid
	if err := r.SetPathParam("udid", o.Udid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
