// Code generated by go-swagger; DO NOT EDIT.

package computers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindComputersByUDIDSubsetReader is a Reader for the FindComputersByUDIDSubset structure.
type FindComputersByUDIDSubsetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindComputersByUDIDSubsetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindComputersByUDIDSubsetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /computers/udid/{udid}/subset/{subset}] findComputersByUDIDSubset", response, response.Code())
	}
}

// NewFindComputersByUDIDSubsetOK creates a FindComputersByUDIDSubsetOK with default headers values
func NewFindComputersByUDIDSubsetOK() *FindComputersByUDIDSubsetOK {
	return &FindComputersByUDIDSubsetOK{}
}

/*
FindComputersByUDIDSubsetOK describes a response with status code 200, with default header values.

OK
*/
type FindComputersByUDIDSubsetOK struct {
	Payload *models.Computer
}

// IsSuccess returns true when this find computers by u d Id subset o k response has a 2xx status code
func (o *FindComputersByUDIDSubsetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find computers by u d Id subset o k response has a 3xx status code
func (o *FindComputersByUDIDSubsetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find computers by u d Id subset o k response has a 4xx status code
func (o *FindComputersByUDIDSubsetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find computers by u d Id subset o k response has a 5xx status code
func (o *FindComputersByUDIDSubsetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find computers by u d Id subset o k response a status code equal to that given
func (o *FindComputersByUDIDSubsetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find computers by u d Id subset o k response
func (o *FindComputersByUDIDSubsetOK) Code() int {
	return 200
}

func (o *FindComputersByUDIDSubsetOK) Error() string {
	return fmt.Sprintf("[GET /computers/udid/{udid}/subset/{subset}][%d] findComputersByUDIdSubsetOK  %+v", 200, o.Payload)
}

func (o *FindComputersByUDIDSubsetOK) String() string {
	return fmt.Sprintf("[GET /computers/udid/{udid}/subset/{subset}][%d] findComputersByUDIdSubsetOK  %+v", 200, o.Payload)
}

func (o *FindComputersByUDIDSubsetOK) GetPayload() *models.Computer {
	return o.Payload
}

func (o *FindComputersByUDIDSubsetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Computer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
