// Code generated by go-swagger; DO NOT EDIT.

package computers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindComputersByUDIDReader is a Reader for the FindComputersByUDID structure.
type FindComputersByUDIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindComputersByUDIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindComputersByUDIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /computers/udid/{udid}] findComputersByUDID", response, response.Code())
	}
}

// NewFindComputersByUDIDOK creates a FindComputersByUDIDOK with default headers values
func NewFindComputersByUDIDOK() *FindComputersByUDIDOK {
	return &FindComputersByUDIDOK{}
}

/*
FindComputersByUDIDOK describes a response with status code 200, with default header values.

OK
*/
type FindComputersByUDIDOK struct {
	Payload *models.Computer
}

// IsSuccess returns true when this find computers by u d Id o k response has a 2xx status code
func (o *FindComputersByUDIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find computers by u d Id o k response has a 3xx status code
func (o *FindComputersByUDIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find computers by u d Id o k response has a 4xx status code
func (o *FindComputersByUDIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find computers by u d Id o k response has a 5xx status code
func (o *FindComputersByUDIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find computers by u d Id o k response a status code equal to that given
func (o *FindComputersByUDIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find computers by u d Id o k response
func (o *FindComputersByUDIDOK) Code() int {
	return 200
}

func (o *FindComputersByUDIDOK) Error() string {
	return fmt.Sprintf("[GET /computers/udid/{udid}][%d] findComputersByUDIdOK  %+v", 200, o.Payload)
}

func (o *FindComputersByUDIDOK) String() string {
	return fmt.Sprintf("[GET /computers/udid/{udid}][%d] findComputersByUDIdOK  %+v", 200, o.Payload)
}

func (o *FindComputersByUDIDOK) GetPayload() *models.Computer {
	return o.Payload
}

func (o *FindComputersByUDIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Computer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
