// Code generated by go-swagger; DO NOT EDIT.

package mobiledeviceprovisioningprofiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindMobileDeviceProvisioningProfilesByIDParams creates a new FindMobileDeviceProvisioningProfilesByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindMobileDeviceProvisioningProfilesByIDParams() *FindMobileDeviceProvisioningProfilesByIDParams {
	return &FindMobileDeviceProvisioningProfilesByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindMobileDeviceProvisioningProfilesByIDParamsWithTimeout creates a new FindMobileDeviceProvisioningProfilesByIDParams object
// with the ability to set a timeout on a request.
func NewFindMobileDeviceProvisioningProfilesByIDParamsWithTimeout(timeout time.Duration) *FindMobileDeviceProvisioningProfilesByIDParams {
	return &FindMobileDeviceProvisioningProfilesByIDParams{
		timeout: timeout,
	}
}

// NewFindMobileDeviceProvisioningProfilesByIDParamsWithContext creates a new FindMobileDeviceProvisioningProfilesByIDParams object
// with the ability to set a context for a request.
func NewFindMobileDeviceProvisioningProfilesByIDParamsWithContext(ctx context.Context) *FindMobileDeviceProvisioningProfilesByIDParams {
	return &FindMobileDeviceProvisioningProfilesByIDParams{
		Context: ctx,
	}
}

// NewFindMobileDeviceProvisioningProfilesByIDParamsWithHTTPClient creates a new FindMobileDeviceProvisioningProfilesByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindMobileDeviceProvisioningProfilesByIDParamsWithHTTPClient(client *http.Client) *FindMobileDeviceProvisioningProfilesByIDParams {
	return &FindMobileDeviceProvisioningProfilesByIDParams{
		HTTPClient: client,
	}
}

/*
FindMobileDeviceProvisioningProfilesByIDParams contains all the parameters to send to the API endpoint

	for the find mobile device provisioning profiles by Id operation.

	Typically these are written to a http.Request.
*/
type FindMobileDeviceProvisioningProfilesByIDParams struct {

	/* ID.

	   Id value to filter by
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find mobile device provisioning profiles by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindMobileDeviceProvisioningProfilesByIDParams) WithDefaults() *FindMobileDeviceProvisioningProfilesByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find mobile device provisioning profiles by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindMobileDeviceProvisioningProfilesByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) WithTimeout(timeout time.Duration) *FindMobileDeviceProvisioningProfilesByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) WithContext(ctx context.Context) *FindMobileDeviceProvisioningProfilesByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) WithHTTPClient(client *http.Client) *FindMobileDeviceProvisioningProfilesByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) WithID(id int64) *FindMobileDeviceProvisioningProfilesByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find mobile device provisioning profiles by Id params
func (o *FindMobileDeviceProvisioningProfilesByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindMobileDeviceProvisioningProfilesByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
