// Code generated by go-swagger; DO NOT EDIT.

package peripheraltypes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/johnmikee/sync2snipe/mdm/jamf/models"
)

// FindPeripheralTypesByIDReader is a Reader for the FindPeripheralTypesByID structure.
type FindPeripheralTypesByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindPeripheralTypesByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindPeripheralTypesByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /peripheraltypes/id/{id}] findPeripheralTypesById", response, response.Code())
	}
}

// NewFindPeripheralTypesByIDOK creates a FindPeripheralTypesByIDOK with default headers values
func NewFindPeripheralTypesByIDOK() *FindPeripheralTypesByIDOK {
	return &FindPeripheralTypesByIDOK{}
}

/*
FindPeripheralTypesByIDOK describes a response with status code 200, with default header values.

OK
*/
type FindPeripheralTypesByIDOK struct {
	Payload *models.PeripheralType
}

// IsSuccess returns true when this find peripheral types by Id o k response has a 2xx status code
func (o *FindPeripheralTypesByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find peripheral types by Id o k response has a 3xx status code
func (o *FindPeripheralTypesByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find peripheral types by Id o k response has a 4xx status code
func (o *FindPeripheralTypesByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find peripheral types by Id o k response has a 5xx status code
func (o *FindPeripheralTypesByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find peripheral types by Id o k response a status code equal to that given
func (o *FindPeripheralTypesByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find peripheral types by Id o k response
func (o *FindPeripheralTypesByIDOK) Code() int {
	return 200
}

func (o *FindPeripheralTypesByIDOK) Error() string {
	return fmt.Sprintf("[GET /peripheraltypes/id/{id}][%d] findPeripheralTypesByIdOK  %+v", 200, o.Payload)
}

func (o *FindPeripheralTypesByIDOK) String() string {
	return fmt.Sprintf("[GET /peripheraltypes/id/{id}][%d] findPeripheralTypesByIdOK  %+v", 200, o.Payload)
}

func (o *FindPeripheralTypesByIDOK) GetPayload() *models.PeripheralType {
	return o.Payload
}

func (o *FindPeripheralTypesByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PeripheralType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
