// Code generated by go-swagger; DO NOT EDIT.

package commandflush

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CommandFlushReader is a Reader for the CommandFlush structure.
type CommandFlushReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CommandFlushReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCommandFlushOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /commandflush] commandFlush", response, response.Code())
	}
}

// NewCommandFlushOK creates a CommandFlushOK with default headers values
func NewCommandFlushOK() *CommandFlushOK {
	return &CommandFlushOK{}
}

/*
CommandFlushOK describes a response with status code 200, with default header values.

OK
*/
type CommandFlushOK struct {
}

// IsSuccess returns true when this command flush o k response has a 2xx status code
func (o *CommandFlushOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this command flush o k response has a 3xx status code
func (o *CommandFlushOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this command flush o k response has a 4xx status code
func (o *CommandFlushOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this command flush o k response has a 5xx status code
func (o *CommandFlushOK) IsServerError() bool {
	return false
}

// IsCode returns true when this command flush o k response a status code equal to that given
func (o *CommandFlushOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the command flush o k response
func (o *CommandFlushOK) Code() int {
	return 200
}

func (o *CommandFlushOK) Error() string {
	return fmt.Sprintf("[DELETE /commandflush][%d] commandFlushOK ", 200)
}

func (o *CommandFlushOK) String() string {
	return fmt.Sprintf("[DELETE /commandflush][%d] commandFlushOK ", 200)
}

func (o *CommandFlushOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
